"""Clip catalog for the LEFT vs RIGHT chess sound-bite pack.

Not a game asset. Local listening library only.

A *bark* is a short line a piece says when you click it on the board.
Taunts are separate: those fire on check / capture / mate.
"""

# catalog speaker -> roster piece id. None = commentator, not a piece.
PIECE_ID = {
    "tate": None,
    "rogan": None,
    "newsom": "newsom",
    "aoc": "aoc",
    "bernie": "sanders",
    "schumer": "schumer",
    "kamala": "harris",
    "warren": "warren",
    "buttigieg": "buttigieg",
    "mamdani": "mamdani",
    "trump": "trump",
    "melania": "melania",
    "mcconnell": "mcconnell",
    "rubio": "rubio",
    "cruz": "cruz",
    "rfk": "rfk",
    "vance": "vance",
    "desantis": "desantis",
}

# Each source is a video we pull audio from.
# url: known YouTube/page. search: yt-dlp ytsearch query if url is missing.
# section: optional "START-END" to fetch only a window (yt-dlp --download-sections).

SOURCES = {
    "tate-piers": {
        "url": "https://www.youtube.com/watch?v=NCeAeMJUXqg",
        "title": "Andrew Tate vs Piers Morgan chess (full match, ~5 min)",
    },
    "tate-bugatti": {
        "url": "https://www.youtube.com/watch?v=jUXGN-ffKlk",
        "title": "What color is your Bugatti? (Thurston, 12s)",
    },
    "tate-pbd": {
        "url": "https://www.youtube.com/watch?v=iv-C4CVGk28",
        "title": "Tate PBD interview 13 Sep 2022",
    },
    "rogan-crazy": {
        "url": "https://www.youtube.com/watch?v=_pN6vSmjWpg",
        "title": "JRE Clips — This is crazy / Jamie pull that up",
    },
    "rogan-bananas": {
        "url": "https://www.youtube.com/watch?v=gqhGi1-816U",
        "title": "JRE MMA Show #176 — It was bananas",
    },
    "rogan-kongo": {
        "search": "Joe Rogan It's over He is out Kongo vs Barry UFC Live 4 comeback",
        "title": "UFC Live 4 Kongo vs Barry booth",
    },
    "rogan-ufc316": {
        "search": "Joe Rogan that was so clean UFC 316 knockout",
        "title": "UFC 316 one-punch KO booth",
    },
    "rogan-dariush": {
        "search": "Joe Rogan Dariush is in real trouble UFC 248 Klose",
        "title": "UFC 248 Dariush vs Klose booth",
    },
    "rogan-shocker": {
        "search": "Joe Rogan What a shocker UFC 294 Fight Companion",
        "title": "UFC 294 Fight Companion",
    },
    "newsom-debate": {
        "url": "https://www.youtube.com/watch?v=p-HRaKmK7Bk",
        "title": "DeSantis Newsom Full Debate Fox News 11/30/23",
    },
    "newsom-fire": {
        "search": "Gavin Newsom fight fire with fire CNN October 2025",
        "title": "Newsom CNN 28 Oct 2025",
    },
    "aoc-floor": {
        "url": "https://www.youtube.com/shorts/rcgw7Nt4L9M",
        "title": "AOC House floor 2 Jul 2025 short",
    },
    "aoc-denver": {
        "url": "https://www.youtube.com/watch?v=C232Zq_MUFA",
        "title": "AOC Denver rally with Bernie Mar 2025",
    },
    "bernie-damn-bill": {
        "search": "Bernie Sanders I wrote the damn bill Tim Ryan CNN debate 2019",
        "title": "CNN Dem debate Detroit 30 Jul 2019",
    },
    "bernie-youre-wrong": {
        "url": "https://www.youtube.com/watch?v=jrh1C0HSRhM",
        "title": "Bernie Sanders begins debate with a fight: You're wrong",
    },
    "bernie-not-me-us": {
        "url": "https://www.youtube.com/watch?v=OADlaeggv14",
        "title": "Not Me. Us. campaign ad",
    },
    "schumer-whirlwind": {
        "url": "https://www.youtube.com/watch?v=qHGrzoS9AbE",
        "title": "Schumer SCOTUS rally 4 Mar 2020",
    },
    "schumer-brooklyn": {
        "search": "Chuck Schumer I'm from Brooklyn we speak in strong language Senate floor March 2020",
        "title": "Schumer Senate floor 5 Mar 2020",
    },
    "kamala-speaking": {
        "search": "Kamala Harris I'm speaking Mr Vice President debate clip",
        "url": "https://www.youtube.com/watch?v=t_G0ia3JOVs",
        "title": "VP debate 7 Oct 2020 — I'm speaking",
        "prefer_short": True,
    },
    "kamala-we-did-it": {
        "url": "https://www.youtube.com/watch?v=H3lpFE19T78",
        "title": "We did it Joe (16s)",
    },
    "kamala-debate-2024": {
        "url": "https://www.youtube.com/watch?v=OQgE0ETV81s",
        "title": "Trump-Harris presidential debate highlights",
    },
    "kamala-coconut": {
        "url": "https://www.youtube.com/watch?v=0bSTqokjNEE",
        "title": "Coconut tree (often ~31:28)",
        "hint_sec": 31 * 60 + 28,
    },
    "warren-bloomberg": {
        "url": "https://www.youtube.com/watch?v=QD4csGWPo6o",
        "title": "Vegas debate 19 Feb 2020 — Mayor Bloomberg",
    },
    "warren-wine-caves": {
        "search": "Elizabeth Warren billionaires in wine caves should not pick the next president debate 2019",
        "title": "LA debate Dec 2019 wine caves",
    },
    "warren-not-silent": {
        "url": "https://www.youtube.com/watch?v=GOEMxZe4tY0",
        "title": "Warren cut off during Sessions debate",
    },
    "warren-plan": {
        "url": "https://www.youtube.com/watch?v=o7y35Jb9cP8",
        "title": "I've Got A Plan For That With Elizabeth Warren",
    },
    "pete-bait": {
        "search": "Pete Buttigieg I know bait when I see it CNN town hall April 2019",
        "title": "CNN town hall 22 Apr 2019",
        "hint_sec": 23 * 60 + 55,
    },
    "pete-quarrel": {
        "url": "https://www.youtube.com/watch?v=hViAbRitbmw",
        "title": "LGBTQ Victory Fund 7 Apr 2019",
    },
    "pete-data": {
        "url": "https://www.youtube.com/watch?v=QzGEotTYsCE",
        "title": "Fox News Sunday Jul 2024",
    },
    "pete-literally": {
        "search": "Pete Buttigieg that's literally not true CNBC March 2024",
        "title": "CNBC Mar 2024",
    },
    "mamdani-victory": {
        "url": "https://www.youtube.com/watch?v=hFH2dYwH3rI",
        "title": "Mamdani NYC victory speech 4 Nov 2025",
    },
    "trump-fired": {
        "url": "https://www.youtube.com/watch?v=8TBkt7os9EY",
        "title": "Comrade Kamala Harris, You're Fired (York / DNC 2024)",
    },
    "trump-jail": {
        "url": "https://www.youtube.com/watch?v=_XzL1sQWRd4",
        "title": "Because you'd be in jail (14s)",
    },
    "trump-nasty": {
        "url": "https://www.youtube.com/watch?v=B2dXhjNRwpE",
        "title": "Such a nasty woman",
    },
    "trump-rnc-2016": {
        "search": "Donald Trump I alone can fix it I am your voice RNC Cleveland 2016 full speech",
        "title": "RNC Cleveland 21 Jul 2016",
    },
    "trump-win-so-much": {
        "url": "https://www.youtube.com/watch?v=nOMPk1N2RiY",
        "title": "We're going to win so much Albany 2016",
    },
    "trump-best-words": {
        "search": "Donald Trump I know words I have the best words South Carolina rally December 2015",
        "title": "SC rally 30 Dec 2015",
    },
    "trump-pwmc": {
        "search": "Trump person woman man camera TV Fox interview 2020",
        "title": "Person Woman Man Camera TV",
    },
    "trump-dogs": {
        "search": "Trump they're eating the dogs they're eating the cats ABC debate September 2024",
        "title": "ABC debate 10 Sep 2024 eating the dogs",
    },
    "trump-little-marco": {
        "search": "Trump don't worry about it Little Marco GOP debate Detroit 2016",
        "title": "Fox GOP debate Detroit 3 Mar 2016",
    },
    "melania-abc": {
        "search": "Melania Trump I don't care ABC 20/20 interview October 2018",
        "title": "ABC 20/20 12 Oct 2018",
    },
    "melania-rnc": {
        "search": "Melania Trump and it won't even be close RNC 2016 speech",
        "title": "2016 RNC 18 Jul 2016",
    },
    "mcconnell-reaper": {
        "url": "https://www.youtube.com/watch?v=w5vIJPSN4zw",
        "title": "McConnell: I am the grim reaper of the Democratic socialist agenda",
    },
    "mcconnell-vacancy": {
        "url": "https://www.youtube.com/watch?v=ZcKYOGWyamY",
        "title": "McConnell: Supreme Court Vacancy Will Not Be Filled This Year",
    },
    "mcconnell-finish": {
        "search": "Mitch McConnell let me finish Face the Nation April 2024",
        "title": "Face the Nation 28 Apr 2024",
    },
    "rubio-dispel": {
        "search": "Marco Rubio let's dispel with this fiction he knows exactly what he's doing GOP debate Manchester 2016",
        "title": "GOP debate Manchester NH 6 Feb 2016",
    },
    "rubio-detroit": {
        "url": "https://www.youtube.com/watch?v=CR0k5xdUxBs",
        "title": "Donald Trump vs Marco Rubio debate highlights Detroit 2016",
    },
    "cruz-coward": {
        "search": "Ted Cruz Donald you're a sniveling coward leave Heidi the hell alone Wisconsin 2016",
        "title": "Cruz Dane WI 24 Mar 2016",
    },
    "cruz-breathe": {
        "search": "Ted Cruz breathe breathe breathe Rubio GOP debate Detroit 2016",
        "title": "Detroit debate 3 Mar 2016 breathe",
    },
    "cruz-carpet": {
        "search": "Ted Cruz we will carpet bomb them into oblivion Iowa 2015",
        "title": "Iowa 5 Dec 2015",
    },
    "cruz-conscience": {
        "url": "https://www.youtube.com/watch?v=orX-rWiMPCE",
        "title": "Vote your conscience RNC 2016",
    },
    "cruz-chump": {
        "search": "Ted Cruz he is playing you for a chump Marion Indiana May 2016",
        "title": "Marion IN 2 May 2016",
    },
    "rfk-lied": {
        "search": "RFK Jr we were lied to about everything Senate Finance September 2025",
        "title": "Senate Finance 4 Sep 2025",
    },
    "rfk-experts": {
        "search": "RFK Kennedy we need to stop trusting the experts Tucker Carlson 2025",
        "title": "Tucker / Fox 2025",
    },
    "rfk-both-right": {
        "search": "RFK Jr they're both right independent presidential campaign announcement October 2023",
        "title": "Independent campaign announcement 9 Oct 2023",
    },
    "rfk-not-ideal": {
        "url": "https://www.youtube.com/watch?v=RTRBVh045m8",
        "title": "RFK Jr. presidential announcement Boston April 2023",
    },
    "vance-cats": {
        "url": "https://www.youtube.com/watch?v=qBTz3n9ZzPA",
        "title": "JD Vance Called People Without Kids Childless Cat Ladies",
    },
    "vance-trash": {
        "search": "JD Vance take out the trash the trash is named Kamala Harris Atlanta rally 2024",
        "title": "Atlanta-area rally ~3 Nov 2024",
    },
    "vance-future": {
        "search": "JD Vance Tim I'm focused on the future VP debate Walz October 2024",
        "title": "VP debate 1 Oct 2024",
    },
    "vance-boneheaded": {
        "url": "https://www.youtube.com/watch?v=lZSAop2-UH8",
        "title": "JD Vance Responds To Controversial Past Comments | The View",
    },
    "desantis-tampa": {
        "url": "https://www.youtube.com/watch?v=xfmrQOXk9bM",
        "title": "DeSantis Tampa victory 8 Nov 2022",
    },
    "desantis-tpusa": {
        "search": "Ron DeSantis I wish the United States a speedy recovery from Biden TPUSA Tampa July 2022",
        "title": "TPUSA Tampa 22 Jul 2022",
    },
}

# phrase: caption-search strings (normalized). First is the spoken line.
# t: pinned start seconds if known.
# t_end: optional pinned end.
# window: "last5" = only search the last 5 minutes of the source.
# handful: True if listed in "If you only cut a handful".

CLIPS = [
    # --- Tate ---
    dict(id="tate-check", speaker="tate", group="commentators", trigger="check", tone="aggressive",
         source="tate-piers", quote="Check.", phrases=["check"], window="last5"),
    dict(id="tate-mate-in-two", speaker="tate", group="commentators", trigger="mate", tone="both",
         source="tate-piers", quote="Mate in two, Piers.", phrases=["mate in two"], window="last5"),
    dict(id="tate-check-mate", speaker="tate", group="commentators", trigger="mate", tone="aggressive",
         source="tate-piers", quote="Check mate.", phrases=["checkmate", "check mate"], window="last5"),
    dict(id="tate-good-game", speaker="tate", group="commentators", trigger="mate", tone="both",
         source="tate-piers", quote="Good game, sir.", phrases=["good game sir"], window="last5"),
    dict(id="tate-everything-your-fault", speaker="tate", group="commentators", trigger="blunder", tone="aggressive",
         source="tate-piers", quote="Absolutely everything is your fault.",
         phrases=["everything is your fault"], window="last5"),
    dict(id="tate-no-luck", speaker="tate", group="commentators", trigger="blunder", tone="aggressive",
         source="tate-piers", quote="There is no luck.", phrases=["there is no luck"], window="last5"),
    dict(id="tate-never-give-up", speaker="tate", group="commentators", trigger="hype", tone="aggressive",
         source="tate-piers", quote="I never ever give up.", phrases=["never ever give up"],
         window="last5", handful=True),
    dict(id="tate-chessboard", speaker="tate", group="commentators", trigger="trash talk", tone="both",
         source="tate-piers", quote="In the chess board of life, I've done pretty good.",
         phrases=["chess board of life", "chessboard of life"], window="last5"),
    dict(id="tate-bugatti", speaker="tate", group="commentators", trigger="trash talk", tone="aggressive",
         source="tate-bugatti", quote="What color is your Bugatti?",
         phrases=["what color is your bugatti", "color is your bugatti"], t=0, handful=True),
    dict(id="tate-fuck-off", speaker="tate", group="commentators", trigger="trash talk", tone="aggressive",
         source="tate-bugatti", quote="Oh, fuck off then.",
         phrases=["fuck off then", "f off then"], window="last3s"),
    dict(id="tate-shit-together", speaker="tate", group="commentators", trigger="hype", tone="aggressive",
         source="tate-pbd", quote="Get your shit together.",
         phrases=["get your shit together", "get your act together"]),
    dict(id="tate-you-are-losing", speaker="tate", group="commentators", trigger="check", tone="aggressive",
         source="tate-pbd", quote="You are losing.", phrases=["you are losing"]),
    # --- Rogan ---
    dict(id="rogan-its-over", speaker="rogan", group="commentators", trigger="capture", tone="booth",
         source="rogan-kongo", quote="It's over!", phrases=["it's over", "its over"]),
    dict(id="rogan-he-is-out", speaker="rogan", group="commentators", trigger="capture", tone="booth",
         source="rogan-kongo", quote="He is out! / Oh, he's out. He's out.",
         phrases=["he's out", "he is out"]),
    dict(id="rogan-comeback", speaker="rogan", group="commentators", trigger="mate", tone="booth",
         source="rogan-kongo", quote="The most amazing comeback I have ever seen.",
         phrases=["most amazing comeback"]),
    dict(id="rogan-so-clean", speaker="rogan", group="commentators", trigger="capture", tone="booth",
         source="rogan-ufc316", quote="That was so clean!", phrases=["so clean"]),
    dict(id="rogan-dariush", speaker="rogan", group="commentators", trigger="check", tone="booth",
         source="rogan-dariush", quote="Dariush is in real trouble.",
         phrases=["dariush is in real trouble", "in real trouble"]),
    dict(id="rogan-omg", speaker="rogan", group="commentators", trigger="mate", tone="booth",
         source="rogan-dariush", quote="Oh my God!", phrases=["oh my god"]),
    dict(id="rogan-crazy", speaker="rogan", group="commentators", trigger="blunder", tone="booth",
         source="rogan-crazy", quote="This is crazy.", phrases=["this is crazy"], t=5),
    dict(id="rogan-jamie", speaker="rogan", group="commentators", trigger="hype", tone="booth",
         source="rogan-crazy", quote="Jamie, pull that up.", phrases=["jamie pull that up", "jamie pull it up"], t=2),
    dict(id="rogan-bananas", speaker="rogan", group="commentators", trigger="blunder", tone="booth",
         source="rogan-bananas", quote="It was bananas.", phrases=["it was bananas", "that's bananas", "that was bananas"]),
    dict(id="rogan-shocker", speaker="rogan", group="commentators", trigger="blunder", tone="booth",
         source="rogan-shocker", quote="What a shocker.", phrases=["what a shocker"]),
    # --- Newsom ---
    dict(id="newsom-hows-that", speaker="newsom", group="left", trigger="trash talk", tone="both",
         source="newsom-debate", quote="How's that going for you, Ron?",
         phrases=["how's that going for you", "how is that going for you"]),
    dict(id="newsom-bully", speaker="newsom", group="left", trigger="capture", tone="aggressive",
         source="newsom-debate", quote="You're nothing but a bully.",
         phrases=["nothing but a bully"], handful=True),
    dict(id="newsom-relax", speaker="newsom", group="left", trigger="got captured", tone="both",
         source="newsom-debate", quote="Again, Ron, relax. I can handle it.",
         phrases=["relax i can handle it", "ron relax"]),
    dict(id="newsom-used-to-bullying", speaker="newsom", group="left", trigger="got captured", tone="funny",
         source="newsom-debate", quote="I'm used to bullying.", phrases=["used to bullying"]),
    dict(id="newsom-spare-me", speaker="newsom", group="left", trigger="trash talk", tone="aggressive",
         source="newsom-debate", quote="Spare me this notion of freedom.",
         phrases=["spare me this notion", "notion of freedom"]),
    dict(id="newsom-fire", speaker="newsom", group="left", trigger="hype", tone="aggressive",
         source="newsom-fire", quote="Fight fire with fire.", phrases=["fight fire with fire"]),
    # --- AOC ---
    dict(id="aoc-lied-to", speaker="aoc", group="left", trigger="blunder", tone="both",
         source="aoc-floor", quote="It doesn't take a smart person to know if you're being lied to.",
         phrases=["doesn't take a smart person", "being lied to"], t=22),
    dict(id="aoc-lying", speaker="aoc", group="left", trigger="check", tone="aggressive",
         source="aoc-floor", quote="You're either being lied to or you are lying.",
         phrases=["being lied to or you are lying", "lied to or you're lying", "or you are lying"]),
    dict(id="aoc-devil", speaker="aoc", group="left", trigger="mate", tone="aggressive",
         source="aoc-floor", quote="This bill is a deal with the devil.",
         phrases=["deal with the devil"]),
    dict(id="aoc-beat-them", speaker="aoc", group="left", trigger="hype", tone="aggressive",
         source="aoc-denver", quote="We are going to beat them.",
         phrases=["going to beat them", "we are going to beat"]),
    # --- Bernie ---
    dict(id="bernie-damn-bill", speaker="bernie", group="left", trigger="capture", tone="both",
         source="bernie-damn-bill", quote="I wrote the damn bill.",
         phrases=["wrote the damn bill"], handful=True),
    dict(id="bernie-youre-wrong", speaker="bernie", group="left", trigger="blunder", tone="aggressive",
         source="bernie-youre-wrong", quote="You're wrong.", phrases=["you're wrong", "you are wrong"]),
    dict(id="bernie-not-me-us", speaker="bernie", group="left", trigger="hype", tone="aggressive",
         source="bernie-not-me-us", quote="Not me. Us.", phrases=["not me us"]),
    # --- Schumer ---
    dict(id="schumer-whirlwind", speaker="schumer", group="left", trigger="check", tone="aggressive",
         source="schumer-whirlwind", quote="You have released the whirlwind.",
         phrases=["released the whirlwind"], t=45),
    dict(id="schumer-pay-the-price", speaker="schumer", group="left", trigger="capture", tone="aggressive",
         source="schumer-whirlwind", quote="You will pay the price.",
         phrases=["pay the price"], t=45),
    dict(id="schumer-what-hit-you", speaker="schumer", group="left", trigger="mate", tone="aggressive",
         source="schumer-whirlwind", quote="You won't know what hit you.",
         phrases=["know what hit you"], handful=True),
    dict(id="schumer-gone-november", speaker="schumer", group="left", trigger="mate", tone="aggressive",
         source="schumer-whirlwind", quote="You're gone in November.",
         phrases=["gone in november"], t=64, t_end=100),
    dict(id="schumer-not-on-our-watch", speaker="schumer", group="left", trigger="got captured", tone="aggressive",
         source="schumer-whirlwind", quote="Not on our watch.", phrases=["not on our watch"], t=100),
    dict(id="schumer-brooklyn", speaker="schumer", group="left", trigger="got captured", tone="both",
         source="schumer-brooklyn", quote="I'm from Brooklyn. We speak in strong language.",
         phrases=["from brooklyn", "speak in strong language"]),
    # --- Kamala ---
    dict(id="kamala-im-speaking", speaker="kamala", group="left", trigger="got captured", tone="both",
         source="kamala-speaking", quote="I'm speaking. / Mr. Vice President, I'm speaking.",
         phrases=["i'm speaking", "i am speaking"], handful=True),
    dict(id="kamala-we-did-it", speaker="kamala", group="left", trigger="mate", tone="funny",
         source="kamala-we-did-it", quote="We did it, Joe.", phrases=["we did it joe"], handful=True),
    dict(id="kamala-running-against-me", speaker="kamala", group="left", trigger="trash talk", tone="both",
         source="kamala-debate-2024", quote="You're running against me.",
         phrases=["running against me"]),
    dict(id="kamala-not-going-back", speaker="kamala", group="left", trigger="hype", tone="aggressive",
         source="kamala-debate-2024", quote="We're not going back.",
         phrases=["we're not going back", "we are not going back"]),
    dict(id="kamala-coconut", speaker="kamala", group="left", trigger="blunder", tone="funny",
         source="kamala-coconut", quote="You think you just fell out of a coconut tree?",
         phrases=["coconut tree", "fell out of a coconut"], t=31 * 60 + 28, handful=True),
    # --- Warren ---
    dict(id="warren-plan", speaker="warren", group="left", trigger="hype", tone="funny",
         source="warren-plan", quote="I have a plan for that.",
         phrases=["i have a plan for that"]),
    dict(id="warren-bloomberg", speaker="warren", group="left", trigger="capture", tone="both",
         source="warren-bloomberg", quote="No, I'm not talking about Donald Trump. I'm talking about Mayor Bloomberg.",
         phrases=["talking about mayor bloomberg", "mayor bloomberg"]),
    dict(id="warren-wine-caves", speaker="warren", group="left", trigger="trash talk", tone="both",
         source="warren-wine-caves", quote="Billionaires in wine caves should not pick the next president.",
         phrases=["wine caves"]),
    dict(id="warren-not-silent", speaker="warren", group="left", trigger="got captured", tone="aggressive",
         source="warren-not-silent", quote="I will not be silent.",
         phrases=["i will not be silent"]),
    # --- Buttigieg ---
    dict(id="pete-bait", speaker="buttigieg", group="left", trigger="blunder", tone="both",
         source="pete-bait", quote="I know bait when I see it, and I'm not going to take it.",
         phrases=["know bait when i see it", "not going to take it"], t=23 * 60 + 55),
    dict(id="pete-quarrel", speaker="buttigieg", group="left", trigger="trash talk", tone="aggressive",
         source="pete-quarrel", quote="Your quarrel, sir, is with my creator.",
         phrases=["quarrel sir", "with my creator"]),
    dict(id="pete-data", speaker="buttigieg", group="left", trigger="trash talk", tone="both",
         source="pete-data", quote="Do yourself a favor and look up the data.",
         phrases=["look up the data", "do yourself a favor"]),
    dict(id="pete-literally", speaker="buttigieg", group="left", trigger="blunder", tone="aggressive",
         source="pete-literally", quote="That's literally not true.",
         phrases=["literally not true"]),
    # --- Mamdani ---
    dict(id="mamdani-volume", speaker="mamdani", group="left", trigger="check", tone="both",
         source="mamdani-victory", quote="Turn the volume up.",
         phrases=["turn the volume up"], handful=True),
    dict(id="mamdani-get-through", speaker="mamdani", group="left", trigger="check", tone="aggressive",
         source="mamdani-victory", quote="To get to any of us, you will have to get through all of us.",
         phrases=["get through all of us"]),
    dict(id="mamdani-dynasty", speaker="mamdani", group="left", trigger="mate", tone="both",
         source="mamdani-victory", quote="We have toppled a political dynasty.",
         phrases=["toppled a political dynasty"]),
    dict(id="mamdani-his-name", speaker="mamdani", group="left", trigger="capture", tone="both",
         source="mamdani-victory", quote="Let tonight be the final time I utter his name.",
         phrases=["utter his name", "final time i utter"]),
    # --- Trump ---
    dict(id="trump-fired", speaker="trump", group="right", trigger="capture", tone="aggressive",
         source="trump-fired", quote="You are fired. Get out.",
         phrases=["you are fired", "you're fired get out"], handful=True),
    dict(id="trump-jail", speaker="trump", group="right", trigger="capture", tone="both",
         source="trump-jail", quote="Because you'd be in jail.",
         phrases=["you'd be in jail", "you would be in jail"], handful=True),
    dict(id="trump-nasty-woman", speaker="trump", group="right", trigger="trash talk", tone="aggressive",
         source="trump-nasty", quote="Such a nasty woman.", phrases=["nasty woman"]),
    dict(id="trump-alone-fix", speaker="trump", group="right", trigger="hype", tone="aggressive",
         source="trump-rnc-2016", quote="I alone can fix it.", phrases=["i alone can fix"]),
    dict(id="trump-your-voice", speaker="trump", group="right", trigger="hype", tone="aggressive",
         source="trump-rnc-2016", quote="I am your voice.", phrases=["i am your voice"]),
    dict(id="trump-win-so-much", speaker="trump", group="right", trigger="hype", tone="both",
         source="trump-win-so-much", quote="We're going to win so much.",
         phrases=["win so much"]),
    dict(id="trump-best-words", speaker="trump", group="right", trigger="blunder", tone="funny",
         source="trump-best-words", quote="I know words. I have the best words.",
         phrases=["i have the best words", "i know words"], handful=True),
    dict(id="trump-pwmc", speaker="trump", group="right", trigger="blunder", tone="funny",
         source="trump-pwmc", quote="Person. Woman. Man. Camera. TV.",
         phrases=["person woman man camera", "woman man camera tv"]),
    dict(id="trump-dogs", speaker="trump", group="right", trigger="blunder", tone="both",
         source="trump-dogs", quote="They're eating the dogs… they're eating the cats.",
         phrases=["eating the dogs", "eating the cats"]),
    dict(id="trump-little-marco", speaker="trump", group="right", trigger="trash talk", tone="both",
         source="trump-little-marco", quote="Don't worry about it, Little Marco.",
         phrases=["little marco"]),
    # --- Melania ---
    dict(id="melania-dont-care", speaker="melania", group="right", trigger="trash talk", tone="both",
         source="melania-abc", quote="I want to show them that I don't care.",
         phrases=["i don't care", "show them that i don't care"]),
    dict(id="melania-wont-stop-me", speaker="melania", group="right", trigger="check", tone="ice-cold",
         source="melania-abc", quote="It will not stop me to do what I feel is right.",
         phrases=["will not stop me", "what i feel is right"]),
    dict(id="melania-wont-be-close", speaker="melania", group="right", trigger="mate", tone="both",
         source="melania-rnc", quote="And it won't even be close.",
         phrases=["won't even be close", "will not even be close"]),
    dict(id="melania-bullied", speaker="melania", group="right", trigger="got captured", tone="both",
         source="melania-abc", quote="I could say that I'm the most bullied person in the world.",
         phrases=["most bullied person"]),
    # --- McConnell ---
    dict(id="mcconnell-reaper", speaker="mcconnell", group="right", trigger="capture", tone="both",
         source="mcconnell-reaper", quote="I am indeed the Grim Reaper.",
         phrases=["grim reaper"], handful=True),
    dict(id="mcconnell-going-anywhere", speaker="mcconnell", group="right", trigger="check", tone="aggressive",
         source="mcconnell-reaper", quote="None of that stuff is going anywhere.",
         phrases=["going anywhere"]),
    dict(id="mcconnell-vacancy", speaker="mcconnell", group="right", trigger="mate", tone="aggressive",
         source="mcconnell-vacancy", quote="Mr. President, you will not fill this Supreme Court vacancy.",
         phrases=["will not fill this supreme court", "supreme court vacancy"]),
    dict(id="mcconnell-let-me-finish", speaker="mcconnell", group="right", trigger="trash talk", tone="aggressive",
         source="mcconnell-finish", quote="Let me finish.", phrases=["let me finish"]),
    # --- Rubio ---
    dict(id="rubio-dispel", speaker="rubio", group="right", trigger="blunder", tone="both",
         source="rubio-dispel", quote="Let's dispel with this fiction…",
         phrases=["dispel with this fiction"], handful=True),
    dict(id="rubio-knows-exactly", speaker="rubio", group="right", trigger="check", tone="aggressive",
         source="rubio-dispel", quote="He knows exactly what he's doing.",
         phrases=["knows exactly what he's doing", "knows exactly what he is doing"]),
    dict(id="rubio-trump-steaks", speaker="rubio", group="right", trigger="trash talk", tone="funny",
         source="rubio-detroit", quote="You ever heard of Trump Steaks?",
         phrases=["trump steaks"]),
    dict(id="rubio-steaks-gone", speaker="rubio", group="right", trigger="capture", tone="both",
         source="rubio-detroit", quote="Trump Steaks is gone.",
         phrases=["steaks is gone", "steaks are gone"]),
    dict(id="rubio-big-donald", speaker="rubio", group="right", trigger="trash talk", tone="funny",
         source="rubio-detroit", quote="Let's hear it, big Donald.",
         phrases=["big donald", "let's hear it"]),
    dict(id="rubio-yoga", speaker="rubio", group="right", trigger="trash talk", tone="funny",
         source="rubio-detroit", quote="When they're done with the yoga, can I answer a question?",
         phrases=["done with the yoga"]),
    # --- Cruz ---
    dict(id="cruz-coward", speaker="cruz", group="right", trigger="trash talk", tone="aggressive",
         source="cruz-coward", quote="Donald, you're a sniveling coward.",
         phrases=["sniveling coward", "snivelling coward"], handful=True),
    dict(id="cruz-heidi", speaker="cruz", group="right", trigger="trash talk", tone="aggressive",
         source="cruz-coward", quote="Leave Heidi the hell alone.",
         phrases=["leave heidi", "hell alone"]),
    dict(id="cruz-breathe", speaker="cruz", group="right", trigger="trash talk", tone="funny",
         source="cruz-breathe", quote="Breathe, breathe, breathe.", phrases=["breathe breathe"]),
    dict(id="cruz-carpet-bomb", speaker="cruz", group="right", trigger="capture", tone="aggressive",
         source="cruz-carpet", quote="We will carpet bomb them into oblivion.",
         phrases=["carpet bomb", "into oblivion"]),
    dict(id="cruz-conscience", speaker="cruz", group="right", trigger="check", tone="both",
         source="cruz-conscience", quote="Vote your conscience.",
         phrases=["vote your conscience"]),
    dict(id="cruz-chump", speaker="cruz", group="right", trigger="trash talk", tone="aggressive",
         source="cruz-chump", quote="He is playing you for a chump.",
         phrases=["playing you for a chump"]),
    # --- RFK ---
    dict(id="rfk-lied-to", speaker="rfk", group="right", trigger="check", tone="aggressive",
         source="rfk-lied", quote="We were lied to about everything.",
         phrases=["lied to about everything"]),
    dict(id="rfk-experts", speaker="rfk", group="right", trigger="trash talk", tone="aggressive",
         source="rfk-experts", quote="We need to stop trusting the experts.",
         phrases=["stop trusting the experts", "trusting the experts"]),
    dict(id="rfk-both-right", speaker="rfk", group="right", trigger="trash talk", tone="funny",
         source="rfk-both-right", quote="They're both right!", phrases=["they're both right", "they are both right"]),
    dict(id="rfk-not-ideal", speaker="rfk", group="right", trigger="blunder", tone="funny",
         source="rfk-not-ideal", quote="I am not an ideal presidential candidate.",
         phrases=["not an ideal presidential candidate"]),
    # --- Vance ---
    dict(id="vance-cat-ladies", speaker="vance", group="right", trigger="trash talk", tone="both",
         source="vance-cats", quote="A bunch of childless cat ladies.",
         phrases=["childless cat ladies"]),
    dict(id="vance-trash", speaker="vance", group="right", trigger="capture", tone="aggressive",
         source="vance-trash", quote="We're going to take out the trash… and the trash is named Kamala Harris.",
         phrases=["take out the trash", "trash is named kamala"]),
    dict(id="vance-future", speaker="vance", group="right", trigger="got captured", tone="both",
         source="vance-future", quote="Tim, I'm focused on the future.",
         phrases=["focused on the future"]),
    dict(id="vance-boneheaded", speaker="vance", group="right", trigger="got captured", tone="funny",
         source="vance-boneheaded", quote="Oh man, my most boneheaded comment.",
         phrases=["boneheaded comment", "bone headed"]),
    # --- DeSantis ---
    dict(id="desantis-woke-dies", speaker="desantis", group="right", trigger="mate", tone="aggressive",
         source="desantis-tampa", quote="Florida is where woke goes to die.",
         phrases=["woke goes to die"], t=6 * 60 + 4, handful=True),
    dict(id="desantis-never-surrender", speaker="desantis", group="right", trigger="check", tone="aggressive",
         source="desantis-tampa", quote="We will never, ever surrender to the woke mob.",
         phrases=["surrender to the woke"], t=6 * 60 + 4),
    dict(id="desantis-begun-to-fight", speaker="desantis", group="right", trigger="hype", tone="aggressive",
         source="desantis-tampa", quote="I have only begun to fight.",
         phrases=["only begun to fight"], t=7 * 60 + 56),
    dict(id="desantis-recovery", speaker="desantis", group="right", trigger="trash talk", tone="both",
         source="desantis-tpusa", quote="I wish the United States of America a speedy recovery from Biden.",
         phrases=["speedy recovery from biden"]),
    dict(id="desantis-end-zone", speaker="desantis", group="right", trigger="capture", tone="both",
         source="desantis-tpusa", quote="It's to put the ball in the end zone.",
         phrases=["ball in the end zone"]),
]
