"""Clip catalog for the LEFT vs RIGHT chess sound-bite pack.

Not a game asset. Local listening library only.

A *bark* is a short line a piece says when you click it on the board.
A *last word* is the line they say when they get taken (trigger="got captured").
A *capture order* is what the king says when ordering a take of that victim
(`target` = roster id, filter chip "Captures").
Taunts are separate: those fire on check / capture / mate.
"""

# catalog speaker -> roster piece id. None = commentator, not a piece.
PIECE_ID = {
    "tate": None,
    "rogan": None,
    "newsom": "newsom",
    "aoc": "aoc",
    "bernie": "sanders",
    "schumer": "schumer",
    "kamala": "harris",
    "warren": "warren",
    "buttigieg": "buttigieg",
    "mamdani": "mamdani",
    "trump": "trump",
    "leavitt": "leavitt",
    "melania": "melania",
    "mcconnell": "mcconnell",
    "rubio": "rubio",
    "cruz": "cruz",
    "paul": "paul",
    "rfk": "rfk",
    "vance": "vance",
    "desantis": "desantis",
    "activist": "activist",
    "maga": "maga",
}

# Roster id -> studio heading for Captures filter.
TARGET_NAME = {
    "harris": "Kamala",
    "aoc": "AOC",
    "sanders": "Bernie",
    "schumer": "Schumer",
    "warren": "Warren",
    "buttigieg": "Mayor Pete",
    "mamdani": "Mamdani",
    "activist": "They/Them Rifle",
    "maga": "MAGA pawn",
    "melania": "Melania",
    "leavitt": "Karoline Leavitt",
    "mcconnell": "McConnell",
    "rubio": "Rubio",
    "cruz": "Cruz",
    "paul": "Rand Paul",
    "rfk": "RFK Jr.",
    "vance": "Vance",
    "desantis": "DeSantis",
}

# Each source is a video we pull audio from.
# url: known YouTube/page. search: yt-dlp ytsearch query if url is missing.
# section: optional "START-END" to fetch only a window (yt-dlp --download-sections).

SOURCES = {
    "tate-piers": {
        "url": "https://www.youtube.com/watch?v=NCeAeMJUXqg",
        "title": "Andrew Tate vs Piers Morgan chess (full match, ~5 min)",
    },
    "tate-bugatti": {
        "url": "https://www.youtube.com/watch?v=jUXGN-ffKlk",
        "title": "What color is your Bugatti? (Thurston, 12s)",
    },
    "tate-pbd": {
        "url": "https://www.youtube.com/watch?v=iv-C4CVGk28",
        "title": "Tate PBD interview 13 Sep 2022",
    },
    "rogan-crazy": {
        "url": "https://www.youtube.com/watch?v=_pN6vSmjWpg",
        "title": "JRE Clips — This is crazy / Jamie pull that up",
    },
    "rogan-bananas": {
        "url": "https://www.youtube.com/watch?v=gqhGi1-816U",
        "title": "JRE MMA Show #176 — It was bananas",
    },
    "rogan-kongo": {
        "search": "Joe Rogan It's over He is out Kongo vs Barry UFC Live 4 comeback",
        "title": "UFC Live 4 Kongo vs Barry booth",
    },
    "rogan-ufc316": {
        "search": "Joe Rogan that was so clean UFC 316 knockout",
        "title": "UFC 316 one-punch KO booth",
    },
    "rogan-dariush": {
        "search": "Joe Rogan Dariush is in real trouble UFC 248 Klose",
        "title": "UFC 248 Dariush vs Klose booth",
    },
    "rogan-shocker": {
        "search": "Joe Rogan What a shocker UFC 294 Fight Companion",
        "title": "UFC 294 Fight Companion",
    },
    "newsom-debate": {
        "url": "https://www.youtube.com/watch?v=p-HRaKmK7Bk",
        "title": "DeSantis Newsom Full Debate Fox News 11/30/23",
    },
    "newsom-fire": {
        "search": "Gavin Newsom fight fire with fire CNN October 2025",
        "title": "Newsom CNN 28 Oct 2025",
    },
    "newsom-davos": {
        "url": "https://www.youtube.com/watch?v=DcESKAYTzng",
        "title": "Newsom says he should have brought 'knee pads' to Davos over leaders' 'pathetic' response to Trump",
    },
    "aoc-floor": {
        "url": "https://www.youtube.com/shorts/rcgw7Nt4L9M",
        "title": "AOC House floor 2 Jul 2025 short",
    },
    "aoc-denver": {
        "url": "https://www.youtube.com/watch?v=C232Zq_MUFA",
        "title": "AOC Denver rally with Bernie Mar 2025",
    },
    "bernie-damn-bill": {
        "search": "Bernie Sanders I wrote the damn bill Tim Ryan CNN debate 2019",
        "title": "CNN Dem debate Detroit 30 Jul 2019",
    },
    "bernie-youre-wrong": {
        "url": "https://www.youtube.com/watch?v=jrh1C0HSRhM",
        "title": "Bernie Sanders begins debate with a fight: You're wrong",
    },
    "bernie-not-me-us": {
        "url": "https://www.youtube.com/watch?v=OADlaeggv14",
        "title": "Not Me. Us. campaign ad",
    },
    "schumer-whirlwind": {
        "url": "https://www.youtube.com/watch?v=qHGrzoS9AbE",
        "title": "Schumer SCOTUS rally 4 Mar 2020",
    },
    "schumer-brooklyn": {
        "search": "Chuck Schumer I'm from Brooklyn we speak in strong language Senate floor March 2020",
        "title": "Schumer Senate floor 5 Mar 2020",
    },
    "kamala-speaking": {
        "search": "Kamala Harris I'm speaking Mr Vice President debate clip",
        "url": "https://www.youtube.com/watch?v=t_G0ia3JOVs",
        "title": "VP debate 7 Oct 2020 — I'm speaking",
        "prefer_short": True,
    },
    "kamala-we-did-it": {
        "url": "https://www.youtube.com/watch?v=H3lpFE19T78",
        "title": "We did it Joe (16s)",
    },
    "kamala-debate-2024": {
        "url": "https://www.youtube.com/watch?v=OQgE0ETV81s",
        "title": "Trump-Harris presidential debate highlights",
    },
    "kamala-coconut": {
        "url": "https://www.youtube.com/watch?v=0bSTqokjNEE",
        "title": "Coconut tree (often ~31:28)",
        "hint_sec": 31 * 60 + 28,
    },
    "warren-bloomberg": {
        "url": "https://www.youtube.com/watch?v=QD4csGWPo6o",
        "title": "Vegas debate 19 Feb 2020 — Mayor Bloomberg",
    },
    "warren-wine-caves": {
        "search": "Elizabeth Warren billionaires in wine caves should not pick the next president debate 2019",
        "title": "LA debate Dec 2019 wine caves",
    },
    "warren-not-silent": {
        "url": "https://www.youtube.com/watch?v=GOEMxZe4tY0",
        "title": "Warren cut off during Sessions debate",
    },
    "warren-plan": {
        "url": "https://www.youtube.com/watch?v=o7y35Jb9cP8",
        "title": "I've Got A Plan For That With Elizabeth Warren",
    },
    "pete-bait": {
        "search": "Pete Buttigieg I know bait when I see it CNN town hall April 2019",
        "title": "CNN town hall 22 Apr 2019",
        "hint_sec": 23 * 60 + 55,
    },
    "pete-quarrel": {
        "url": "https://www.youtube.com/watch?v=hViAbRitbmw",
        "title": "LGBTQ Victory Fund 7 Apr 2019",
    },
    "pete-data": {
        "url": "https://www.youtube.com/watch?v=QzGEotTYsCE",
        "title": "Fox News Sunday Jul 2024",
    },
    "pete-literally": {
        "search": "Pete Buttigieg that's literally not true CNBC March 2024",
        "title": "CNBC Mar 2024",
    },
    "mamdani-victory": {
        "url": "https://www.youtube.com/watch?v=hFH2dYwH3rI",
        "title": "Mamdani NYC victory speech 4 Nov 2025",
    },
    "trump-iran-oblit": {
        "url": "https://www.youtube.com/watch?v=J0gAcGoyJ5Y",
        "title": "Air Force Is Gone, The Navy Is Gone: Trump Says Iranian Military Literally Obliterated",
    },
    "leavitt-protests": {
        "url": "https://www.youtube.com/watch?v=YlgLM_ggoio",
        "title": "Karoline Leavitt's 10 most BIZARRE moments as White House press secretary",
        "section": "*0:00-0:45",
    },
    "trump-fired": {
        "url": "https://www.youtube.com/watch?v=8TBkt7os9EY",
        "title": "Comrade Kamala Harris, You're Fired (York / DNC 2024)",
    },
    "trump-jail": {
        "url": "https://www.youtube.com/watch?v=_XzL1sQWRd4",
        "title": "Because you'd be in jail (14s)",
    },
    "trump-nasty": {
        "url": "https://www.youtube.com/watch?v=B2dXhjNRwpE",
        "title": "Such a nasty woman",
    },
    "trump-rnc-2016": {
        "search": "Donald Trump I alone can fix it I am your voice RNC Cleveland 2016 full speech",
        "title": "RNC Cleveland 21 Jul 2016",
    },
    "trump-win-so-much": {
        "url": "https://www.youtube.com/watch?v=nOMPk1N2RiY",
        "title": "We're going to win so much Albany 2016",
    },
    "trump-best-words": {
        "search": "Donald Trump I know words I have the best words South Carolina rally December 2015",
        "title": "SC rally 30 Dec 2015",
    },
    "trump-pwmc": {
        "search": "Trump person woman man camera TV Fox interview 2020",
        "title": "Person Woman Man Camera TV",
    },
    "trump-dogs": {
        "search": "Trump they're eating the dogs they're eating the cats ABC debate September 2024",
        "title": "ABC debate 10 Sep 2024 eating the dogs",
    },
    "trump-little-marco": {
        "search": "Trump don't worry about it Little Marco GOP debate Detroit 2016",
        "title": "Fox GOP debate Detroit 3 Mar 2016",
    },
    "melania-abc": {
        "search": "Melania Trump I don't care ABC 20/20 interview October 2018",
        "title": "ABC 20/20 12 Oct 2018",
    },
    "melania-rnc": {
        "search": "Melania Trump and it won't even be close RNC 2016 speech",
        "title": "2016 RNC 18 Jul 2016",
    },
    "mcconnell-reaper": {
        "url": "https://www.youtube.com/watch?v=w5vIJPSN4zw",
        "title": "McConnell: I am the grim reaper of the Democratic socialist agenda",
    },
    "mcconnell-vacancy": {
        "url": "https://www.youtube.com/watch?v=ZcKYOGWyamY",
        "title": "McConnell: Supreme Court Vacancy Will Not Be Filled This Year",
    },
    "mcconnell-finish": {
        "search": "Mitch McConnell let me finish Face the Nation April 2024",
        "title": "Face the Nation 28 Apr 2024",
    },
    "rubio-dispel": {
        "search": "Marco Rubio let's dispel with this fiction he knows exactly what he's doing GOP debate Manchester 2016",
        "title": "GOP debate Manchester NH 6 Feb 2016",
    },
    "rubio-detroit": {
        "url": "https://www.youtube.com/watch?v=zCKvd0ozx84",
        "title": "Yoga on the debate stage? Rubio: Trump is very flexible",
    },
    "rubio-diplomacy": {
        "url": "https://www.youtube.com/watch?v=mV5cXhdNw3U",
        "title": "Marco Rubio's HEATED moments with Senate on Iran, outbreaks, missing funds | MS NOW Highlights",
        "section": "*20:35-21:35",
    },
    "cruz-coward": {
        "search": "Ted Cruz Donald you're a sniveling coward leave Heidi the hell alone Wisconsin 2016",
        "title": "Cruz Dane WI 24 Mar 2016",
    },
    "cruz-breathe": {
        "search": "Ted Cruz breathe breathe breathe Rubio GOP debate Detroit 2016",
        "title": "Detroit debate 3 Mar 2016 breathe",
    },
    "cruz-carpet": {
        "search": "Ted Cruz we will carpet bomb them into oblivion Iowa 2015",
        "title": "Iowa 5 Dec 2015",
    },
    "cruz-conscience": {
        "url": "https://www.youtube.com/watch?v=orX-rWiMPCE",
        "title": "Vote your conscience RNC 2016",
    },
    "cruz-chump": {
        "search": "Ted Cruz he is playing you for a chump Marion Indiana May 2016",
        "title": "Marion IN 2 May 2016",
    },
    "paul-fauci": {
        "url": "https://www.youtube.com/watch?v=4bC-rF2ymK0",
        "title": "Sen. Paul opening statement, Fauci hearing",
    },
    "rfk-lied": {
        "search": "RFK Jr we were lied to about everything Senate Finance September 2025",
        "title": "Senate Finance 4 Sep 2025",
    },
    "rfk-experts": {
        "search": "RFK Kennedy we need to stop trusting the experts Tucker Carlson 2025",
        "title": "Tucker / Fox 2025",
    },
    "rfk-both-right": {
        "search": "RFK Jr they're both right independent presidential campaign announcement October 2023",
        "title": "Independent campaign announcement 9 Oct 2023",
    },
    "rfk-not-ideal": {
        "url": "https://www.youtube.com/watch?v=RTRBVh045m8",
        "title": "RFK Jr. presidential announcement Boston April 2023",
    },
    "jre-2461": {
        "url": "https://www.youtube.com/watch?v=wk7DQom821s",
        "title": "Joe Rogan Experience #2461 — Robert F. Kennedy, Jr. (27 Feb 2026)",
    },
    "vance-cats": {
        "url": "https://www.youtube.com/watch?v=qBTz3n9ZzPA",
        "title": "JD Vance Called People Without Kids Childless Cat Ladies",
    },
    "vance-trash": {
        "search": "JD Vance take out the trash the trash is named Kamala Harris Atlanta rally 2024",
        "title": "Atlanta-area rally ~3 Nov 2024",
    },
    "vance-future": {
        "search": "JD Vance Tim I'm focused on the future VP debate Walz October 2024",
        "title": "VP debate 1 Oct 2024",
    },
    "vance-boneheaded": {
        "url": "https://www.youtube.com/watch?v=lZSAop2-UH8",
        "title": "JD Vance Responds To Controversial Past Comments | The View",
    },
    "desantis-tampa": {
        "url": "https://www.youtube.com/watch?v=xfmrQOXk9bM",
        "title": "DeSantis Tampa victory 8 Nov 2022",
    },
    "desantis-tpusa": {
        "search": "Ron DeSantis I wish the United States a speedy recovery from Biden TPUSA Tampa July 2022",
        "title": "TPUSA Tampa 22 Jul 2022",
    },
    "trump-no-responsibility": {
        "url": "https://www.youtube.com/watch?v=5Cs_1iYWIhI",
        "title": "Trump: I don't take responsibility at all (Rose Garden, 44s)",
    },
    "newsom-french-laundry": {
        "url": "https://www.youtube.com/watch?v=Ox-X2Mfy5aY",
        "title": "Newsom French Laundry apology — I made a bad mistake",
    },
    "cruz-cancun": {
        "url": "https://www.youtube.com/watch?v=RjOwFadA6wg",
        "title": "Cruz: Cancun trip was obviously a mistake (Bloomberg, 1:26)",
    },
    "desantis-suspend": {
        "url": "https://www.youtube.com/watch?v=MHhoX8kMH1o",
        "title": "DeSantis suspends campaign (WaPo, 43s)",
    },
    "bernie-once-again": {
        "url": "https://www.youtube.com/watch?v=c_OfMjvQ2-M",
        "title": "Bernie: I am once again asking for your financial support",
    },
    "aoc-bartender": {
        "url": "https://www.youtube.com/watch?v=43sh0TySHHE",
        "title": "AOC: I'm proud to be a bartender (CBS, 0:37)",
    },
    "mcconnell-last-term": {
        "url": "https://www.youtube.com/watch?v=lw0s3AT6zjE",
        "title": "McConnell: I will not seek this honor an eighth time (AP, 59s)",
    },
    "kamala-unburdened": {
        "url": "https://www.youtube.com/watch?v=x3fCeabLoO4",
        "title": "Kamala: unburdened by what has been (official, 1:21)",
    },
    "kamala-doac": {
        "url": "https://www.youtube.com/watch?v=D3lhrrXb4WI",
        "title": "Kamala Harris — Diary of a CEO (Steven Bartlett, 30 Oct 2025)",
    },
    "schumer-wrong-words": {
        "search": "Chuck Schumer I should not have used the words I used Senate floor March 5 2020",
        "title": "Schumer walk-back 5 Mar 2020",
    },
    "trump-pocahontas": {
        "url": "https://www.youtube.com/watch?v=YAP9vWl0mAk",
        "title": "Trump Pocahontas crack at Navajo code talkers (CNN, 4:02)",
    },
    "trump-lyin-kamala": {
        "url": "https://www.youtube.com/watch?v=7m4VNYxjNV0",
        "title": "Charlotte NC rally Jul 2024 — Lyin' Kamala (TOI, 58s)",
    },
    "trump-comrade-kamala": {
        "url": "https://www.youtube.com/watch?v=JWOmA_SoyZA",
        "title": "Las Vegas rally 13 Sep 2024 — Comrade Kamala (Forbes, 2:22)",
    },
    "trump-crazy-bernie": {
        "url": "https://www.youtube.com/watch?v=7dqootql9t8",
        "title": "MSG rally Oct 2024 — Crazy Bernie Sanders (Forbes, 6:34)",
    },
    "trump-cryin-chuck": {
        "url": "https://www.youtube.com/watch?v=TiHBXhFSX1U",
        "title": "WHCD 2026 — Chuck Schumer, crying Chuck (TOI, 9:42)",
    },
    "trump-aoc-plus": {
        "url": "https://www.youtube.com/watch?v=XpaQrcl4D-Y",
        "title": "Michigan rally — Trump slams AOC Plus 3 (6:18)",
    },
    "trump-vegas-2020": {
        "url": "https://www.youtube.com/watch?v=ZsyCQTX0UfE",
        "title": "Vegas rally Feb 2020 — Crazy Bernie, Pocahontas, Alfred E. Neuman (AP, 3:19)",
    },
    "trump-mamdani-communist": {
        "url": "https://www.youtube.com/watch?v=Pxw8TdxleDk",
        "title": "America250 Des Moines 3 Jul 2025 — communist at the highest level",
    },
    "trump-radical-left": {
        "url": "https://www.youtube.com/watch?v=D7vIqXQ0xIA",
        "title": "Racine WI rally Jun 2024 — radical left lunatics (FOX 11)",
        "section": "*1:20-1:50",
    },
    "trump-msg-lunatic": {
        "url": "https://www.youtube.com/watch?v=7dqootql9t8",
        "title": "MSG rally Oct 2024 — radical left lunatic (Forbes, 6:34)",
    },
    "newsom-phonies": {
        "url": "https://www.youtube.com/watch?v=J-lGBaOj5m0",
        "title": "Psaki / MS NOW — Newsom on Vance and Rubio phonies (8:10)",
    },
    "newsom-outtrump-short": {
        "url": "https://www.youtube.com/watch?v=EEI6YTu_YeU",
        "title": "DeSantis Newsom debate in 60s (AP) — how's that going for you Ron",
    },
    "newsom-knees": {
        "url": "https://www.youtube.com/watch?v=kCvVOOHaJKg",
        "title": "Newsom press event — knees sore from groveling (official, 24:41)",
    },
    "newsom-cancun-cruz": {
        "search": "Gavin Newsom Cancun Cruz spoken interview not tweet",
        "title": "Newsom saying Cancun Cruz — tweet only, no spoken take found",
    },
}

# phrase: caption-search strings (normalized). First is the spoken line.
# t: pinned start seconds if known.
# t_end: optional pinned end.
# window: "last5" = only search the last 5 minutes of the source.
# handful: True if listed in "If you only cut a handful".

CLIPS = [
    # --- Tate ---
    dict(id="tate-check", speaker="tate", group="commentators", trigger="check", tone="aggressive",
         source="tate-piers", quote="Check.", phrases=["check"], window="last5"),
    dict(id="tate-mate-in-two", speaker="tate", group="commentators", trigger="mate", tone="both",
         source="tate-piers", quote="Mate in two, Piers.", phrases=["mate in two"], window="last5"),
    dict(id="tate-check-mate", speaker="tate", group="commentators", trigger="mate", tone="aggressive",
         source="tate-piers", quote="Check mate.", phrases=["checkmate", "check mate"], window="last5"),
    dict(id="tate-good-game", speaker="tate", group="commentators", trigger="mate", tone="both",
         source="tate-piers", quote="Good game, sir.", phrases=["good game sir"], window="last5"),
    dict(id="tate-everything-your-fault", speaker="tate", group="commentators", trigger="blunder", tone="aggressive",
         source="tate-piers", quote="Absolutely everything is your fault.",
         phrases=["everything is your fault"], window="last5"),
    dict(id="tate-no-luck", speaker="tate", group="commentators", trigger="blunder", tone="aggressive",
         source="tate-piers", quote="There is no luck.", phrases=["there is no luck"], window="last5"),
    dict(id="tate-never-give-up", speaker="tate", group="commentators", trigger="hype", tone="aggressive",
         source="tate-piers", quote="I never ever give up.", phrases=["never ever give up"],
         window="last5", handful=True),
    dict(id="tate-chessboard", speaker="tate", group="commentators", trigger="trash talk", tone="both",
         source="tate-piers", quote="In the chess board of life, I've done pretty good.",
         phrases=["chess board of life", "chessboard of life"], window="last5"),
    dict(id="tate-bugatti", speaker="tate", group="commentators", trigger="trash talk", tone="aggressive",
         source="tate-bugatti", quote="What color is your Bugatti?",
         phrases=["what color is your bugatti", "color is your bugatti"], t=0, handful=True),
    dict(id="tate-fuck-off", speaker="tate", group="commentators", trigger="trash talk", tone="aggressive",
         source="tate-bugatti", quote="Oh, fuck off then.",
         phrases=["fuck off then", "f off then"], window="last3s"),
    dict(id="tate-shit-together", speaker="tate", group="commentators", trigger="hype", tone="aggressive",
         source="tate-pbd", quote="Get your shit together.",
         phrases=["get your shit together", "get your act together"]),
    dict(id="tate-you-are-losing", speaker="tate", group="commentators", trigger="check", tone="aggressive",
         source="tate-pbd", quote="You are losing.", phrases=["you are losing"]),
    # --- Rogan ---
    dict(id="rogan-its-over", speaker="rogan", group="commentators", trigger="capture", tone="booth",
         source="rogan-kongo", quote="It's over!", phrases=["it's over", "its over"]),
    dict(id="rogan-he-is-out", speaker="rogan", group="commentators", trigger="capture", tone="booth",
         source="rogan-kongo", quote="He is out! / Oh, he's out. He's out.",
         phrases=["he's out", "he is out"]),
    dict(id="rogan-comeback", speaker="rogan", group="commentators", trigger="mate", tone="booth",
         source="rogan-kongo", quote="The most amazing comeback I have ever seen.",
         phrases=["most amazing comeback"]),
    dict(id="rogan-so-clean", speaker="rogan", group="commentators", trigger="capture", tone="booth",
         source="rogan-ufc316", quote="That was so clean!", phrases=["so clean"]),
    dict(id="rogan-dariush", speaker="rogan", group="commentators", trigger="check", tone="booth",
         source="rogan-dariush", quote="Dariush is in real trouble.",
         phrases=["dariush is in real trouble", "in real trouble"]),
    dict(id="rogan-omg", speaker="rogan", group="commentators", trigger="mate", tone="booth",
         source="rogan-dariush", quote="Oh my God!", phrases=["oh my god"]),
    dict(id="rogan-crazy", speaker="rogan", group="commentators", trigger="blunder", tone="booth",
         source="rogan-crazy", quote="This is crazy.", phrases=["this is crazy"], t=5),
    dict(id="rogan-jamie", speaker="rogan", group="commentators", trigger="hype", tone="booth",
         source="rogan-crazy", quote="Jamie, pull that up.", phrases=["jamie pull that up", "jamie pull it up"], t=2),
    dict(id="rogan-bananas", speaker="rogan", group="commentators", trigger="blunder", tone="booth",
         source="rogan-bananas", quote="It was bananas.", phrases=["it was bananas", "that's bananas", "that was bananas"]),
    dict(id="rogan-shocker", speaker="rogan", group="commentators", trigger="blunder", tone="booth",
         source="rogan-shocker", quote="What a shocker.", phrases=["what a shocker"]),
    # --- Newsom ---
    dict(id="newsom-hows-that", speaker="newsom", group="left", trigger="trash talk", tone="both",
         source="newsom-debate", quote="How's that going for you, Ron?",
         phrases=["how's that going for you", "how is that going for you"],
         target="desantis"),
    dict(id="newsom-bully", speaker="newsom", group="left", trigger="capture", tone="aggressive",
         source="newsom-debate", quote="You're nothing but a bully.",
         phrases=["nothing but a bully"], handful=True),
    dict(id="newsom-relax", speaker="newsom", group="left", trigger="got captured", tone="both",
         source="newsom-debate", quote="Again, Ron, relax. I can handle it.",
         phrases=["relax i can handle it", "ron relax"], fate="captured"),
    dict(id="newsom-used-to-bullying", speaker="newsom", group="left", trigger="got captured", tone="funny",
         source="newsom-debate", quote="I'm used to bullying.", phrases=["used to bullying"], fate="captured"),
    dict(id="newsom-spare-me", speaker="newsom", group="left", trigger="trash talk", tone="aggressive",
         source="newsom-debate", quote="Spare me this notion of freedom.",
         phrases=["spare me this notion", "notion of freedom"]),
    dict(id="newsom-fire", speaker="newsom", group="left", trigger="hype", tone="aggressive",
         source="newsom-fire", quote="Fight fire with fire.", phrases=["fight fire with fire"]),
    dict(id="newsom-bad-mistake", speaker="newsom", group="left", trigger="got captured", tone="funny",
         source="newsom-french-laundry", quote="I made a bad mistake.",
         phrases=["i made a bad mistake", "made a bad mistake"], handful=True, fate="captured"),
    dict(id="newsom-knee-pads-leaders", speaker="newsom", group="left", trigger="trash talk", tone="funny",
         source="newsom-davos",
         quote="I should have brought up a bunch of knee pads for all the world leaders.",
         phrases=["knee pads for all the world leaders", "bunch of knee pads"],
         t=49.0, t_end=52.5, handful=True),
    dict(id="newsom-trex", speaker="newsom", group="left", trigger="trash talk", tone="funny",
         source="newsom-davos",
         quote="He's a T-Rex. You mate with him or he devours you.",
         phrases=["he's a t-rex", "t-rex", "devours you"],
         t=90.0, t_end=95.0, handful=True),
    dict(id="newsom-not-diplomacy", speaker="newsom", group="left", trigger="trash talk", tone="aggressive",
         source="newsom-davos",
         quote="This is not diplomacy. This is stupidity.",
         phrases=["not diplomacy", "this is stupidity"],
         t=186.0, t_end=188.5, handful=True),
    # --- AOC ---
    dict(id="aoc-lied-to", speaker="aoc", group="left", trigger="blunder", tone="both",
         source="aoc-floor", quote="It doesn't take a smart person to know if you're being lied to.",
         phrases=["doesn't take a smart person", "being lied to"], t=22),
    dict(id="aoc-lying", speaker="aoc", group="left", trigger="check", tone="aggressive",
         source="aoc-floor", quote="You're either being lied to or you are lying.",
         phrases=["being lied to or you are lying", "lied to or you're lying", "or you are lying"]),
    dict(id="aoc-devil", speaker="aoc", group="left", trigger="mate", tone="aggressive",
         source="aoc-floor", quote="This bill is a deal with the devil.",
         phrases=["deal with the devil"]),
    dict(id="aoc-beat-them", speaker="aoc", group="left", trigger="hype", tone="aggressive",
         source="aoc-denver", quote="We are going to beat them.",
         phrases=["going to beat them", "we are going to beat"]),
    dict(id="aoc-bartender", speaker="aoc", group="left", trigger="got captured", tone="funny",
         source="aoc-bartender", quote="I'm proud to be a bartender. Ain't nothing wrong with that.",
         phrases=["proud to be a bartender", "ain't nothing wrong with that"],
         handful=True, fate="fired"),
    # --- Bernie ---
    dict(id="bernie-damn-bill", speaker="bernie", group="left", trigger="capture", tone="both",
         source="bernie-damn-bill", quote="I wrote the damn bill.",
         phrases=["wrote the damn bill"], handful=True),
    dict(id="bernie-youre-wrong", speaker="bernie", group="left", trigger="blunder", tone="aggressive",
         source="bernie-youre-wrong", quote="You're wrong.", phrases=["you're wrong", "you are wrong"]),
    dict(id="bernie-not-me-us", speaker="bernie", group="left", trigger="got captured", tone="aggressive",
         source="bernie-not-me-us", quote="Not me. Us.", phrases=["not me us"], fate="captured"),
    dict(id="bernie-once-again", speaker="bernie", group="left", trigger="got captured", tone="funny",
         source="bernie-once-again", quote="I am once again asking for your financial support.",
         phrases=["once again asking", "asking for your financial support"], handful=True, fate="captured"),
    # --- Schumer ---
    dict(id="schumer-whirlwind", speaker="schumer", group="left", trigger="check", tone="aggressive",
         source="schumer-whirlwind", quote="You have released the whirlwind.",
         phrases=["released the whirlwind"], t=45),
    dict(id="schumer-pay-the-price", speaker="schumer", group="left", trigger="capture", tone="aggressive",
         source="schumer-whirlwind", quote="You will pay the price.",
         phrases=["pay the price"], t=45),
    dict(id="schumer-what-hit-you", speaker="schumer", group="left", trigger="mate", tone="aggressive",
         source="schumer-whirlwind", quote="You won't know what hit you.",
         phrases=["know what hit you"], handful=True),
    dict(id="schumer-gone-november", speaker="schumer", group="left", trigger="mate", tone="aggressive",
         source="schumer-whirlwind", quote="You're gone in November.",
         phrases=["gone in november"], t=64, t_end=100),
    dict(id="schumer-not-on-our-watch", speaker="schumer", group="left", trigger="got captured", tone="aggressive",
         source="schumer-whirlwind", quote="Not on our watch.", phrases=["not on our watch"], t=100,
         fate="captured"),
    dict(id="schumer-brooklyn", speaker="schumer", group="left", trigger="got captured", tone="both",
         source="schumer-brooklyn", quote="I'm from Brooklyn. We speak in strong language.",
         phrases=["from brooklyn", "speak in strong language"], fate="captured"),
    dict(id="schumer-wrong-words", speaker="schumer", group="left", trigger="got captured", tone="funny",
         source="schumer-wrong-words", quote="I should not have used the words I used.",
         phrases=["should not have used the words", "shouldn't have used the words"], fate="captured"),
    # --- Kamala ---
    dict(id="kamala-im-speaking", speaker="kamala", group="left", trigger="got captured", tone="both",
         source="kamala-speaking", quote="I'm speaking. / Mr. Vice President, I'm speaking.",
         phrases=["i'm speaking", "i am speaking"], handful=True, fate="captured"),
    dict(id="kamala-we-did-it", speaker="kamala", group="left", trigger="mate", tone="funny",
         source="kamala-we-did-it", quote="We did it, Joe.", phrases=["we did it joe"], handful=True),
    dict(id="kamala-running-against-me", speaker="kamala", group="left", trigger="trash talk", tone="both",
         source="kamala-debate-2024", quote="You're running against me.",
         phrases=["running against me"]),
    dict(id="kamala-not-going-back", speaker="kamala", group="left", trigger="hype", tone="aggressive",
         source="kamala-debate-2024", quote="We're not going back.",
         phrases=["we're not going back", "we are not going back"]),
    dict(id="kamala-coconut", speaker="kamala", group="left", trigger="got captured", tone="funny",
         source="kamala-coconut", quote="You think you just fell out of a coconut tree?",
         phrases=["coconut tree", "fell out of a coconut"], t=31 * 60 + 28, handful=True, fate="captured"),
    dict(id="kamala-unburdened", speaker="kamala", group="left", trigger="got captured", tone="funny",
         source="kamala-unburdened", quote="What can be, unburdened by what has been.",
         phrases=["unburdened by what has been"], fate="captured"),
    dict(id="kamala-doac-troubling", speaker="kamala", group="left", trigger="got captured", tone="funny",
         source="kamala-doac", quote="It's a troubling time.",
         phrases=["troubling time", "it's a troubling time"], t=143, handful=True, fate="captured"),
    dict(id="kamala-doac-worse", speaker="kamala", group="left", trigger="got captured", tone="funny",
         source="kamala-doac", quote="It may get worse before it gets better.",
         phrases=["worse before it gets better", "get worse before it gets"], t=187, fate="captured"),
    dict(id="kamala-doac-different", speaker="kamala", group="left", trigger="got captured", tone="both",
         source="kamala-doac", quote="I do think about how different it could have been.",
         phrases=["how different it could have been", "different it could have been"], t=246, fate="captured"),
    dict(id="kamala-doac-shock", speaker="kamala", group="left", trigger="got captured", tone="funny",
         source="kamala-doac", quote="I was in a state of shock.",
         phrases=["state of shock", "i was in a state of shock"], t=61, handful=True, fate="captured"),
    dict(id="kamala-doac-my-god", speaker="kamala", group="left", trigger="got captured", tone="funny",
         source="kamala-doac", quote="My God, my God, my God.",
         phrases=["my god my god", "my god, my god"], t=4363, fate="captured"),
    dict(id="kamala-doac-more-time", speaker="kamala", group="left", trigger="got captured", tone="funny",
         source="kamala-doac", quote="I wish we had more time.",
         phrases=["wish we had more time", "i wish we had more time"], t=5376, handful=True, fate="captured"),
    # --- Warren ---
    dict(id="warren-plan", speaker="warren", group="left", trigger="got captured", tone="funny",
         source="warren-plan", quote="I have a plan for that.",
         phrases=["i have a plan for that"], fate="captured"),
    dict(id="warren-bloomberg", speaker="warren", group="left", trigger="capture", tone="both",
         source="warren-bloomberg", quote="No, I'm not talking about Donald Trump. I'm talking about Mayor Bloomberg.",
         phrases=["talking about mayor bloomberg", "mayor bloomberg"]),
    dict(id="warren-wine-caves", speaker="warren", group="left", trigger="trash talk", tone="both",
         source="warren-wine-caves", quote="Billionaires in wine caves should not pick the next president.",
         phrases=["wine caves"]),
    dict(id="warren-not-silent", speaker="warren", group="left", trigger="got captured", tone="aggressive",
         source="warren-not-silent", quote="I will not be silent.",
         phrases=["i will not be silent"], fate="captured"),
    # --- Buttigieg ---
    dict(id="pete-bait", speaker="buttigieg", group="left", trigger="blunder", tone="both",
         source="pete-bait", quote="I know bait when I see it, and I'm not going to take it.",
         phrases=["know bait when i see it", "not going to take it"], t=23 * 60 + 55),
    dict(id="pete-quarrel", speaker="buttigieg", group="left", trigger="got captured", tone="aggressive",
         source="pete-quarrel", quote="Your quarrel, sir, is with my creator.",
         phrases=["quarrel sir", "with my creator"], fate="captured"),
    dict(id="pete-data", speaker="buttigieg", group="left", trigger="trash talk", tone="both",
         source="pete-data", quote="Do yourself a favor and look up the data.",
         phrases=["look up the data", "do yourself a favor"]),
    dict(id="pete-literally", speaker="buttigieg", group="left", trigger="blunder", tone="aggressive",
         source="pete-literally", quote="That's literally not true.",
         phrases=["literally not true"]),
    # --- Mamdani ---
    dict(id="mamdani-volume", speaker="mamdani", group="left", trigger="got captured", tone="both",
         source="mamdani-victory", quote="Turn the volume up.",
         phrases=["turn the volume up"], handful=True, fate="captured"),
    dict(id="mamdani-get-through", speaker="mamdani", group="left", trigger="check", tone="aggressive",
         source="mamdani-victory", quote="To get to any of us, you will have to get through all of us.",
         phrases=["get through all of us"]),
    dict(id="mamdani-dynasty", speaker="mamdani", group="left", trigger="mate", tone="both",
         source="mamdani-victory", quote="We have toppled a political dynasty.",
         phrases=["toppled a political dynasty"]),
    dict(id="mamdani-his-name", speaker="mamdani", group="left", trigger="capture", tone="both",
         source="mamdani-victory", quote="Let tonight be the final time I utter his name.",
         phrases=["utter his name", "final time i utter"]),
    dict(id="mamdani-no-apology", speaker="mamdani", group="left", trigger="got captured", tone="both",
         source="mamdani-victory", quote="I refuse to apologize.",
         phrases=["refuse to apologize", "i refuse to apologize"], fate="captured"),
    # --- Trump ---
    dict(id="trump-fired", speaker="trump", group="right", trigger="capture", tone="aggressive",
         source="trump-fired", quote="You are fired. Get out.",
         phrases=["you are fired", "you're fired get out"], handful=True, target="harris"),
    dict(id="trump-jail", speaker="trump", group="right", trigger="capture", tone="both",
         source="trump-jail", quote="Because you'd be in jail.",
         phrases=["you'd be in jail", "you would be in jail"], handful=True),
    dict(id="trump-nasty-woman", speaker="trump", group="right", trigger="trash talk", tone="aggressive",
         source="trump-nasty", quote="Such a nasty woman.", phrases=["nasty woman"]),
    dict(id="trump-alone-fix", speaker="trump", group="right", trigger="hype", tone="aggressive",
         source="trump-rnc-2016", quote="I alone can fix it.", phrases=["i alone can fix"]),
    dict(id="trump-obliterated", speaker="trump", group="right", trigger="hype", tone="aggressive",
         source="trump-iran-oblit", quote="Obliterated. The air force is gone. The navy is gone.",
         phrases=["air force is gone", "navy is gone", "literally obliterated"], handful=True),
    dict(id="trump-your-voice", speaker="trump", group="right", trigger="hype", tone="aggressive",
         source="trump-rnc-2016", quote="I am your voice.", phrases=["i am your voice"]),
    dict(id="trump-win-so-much", speaker="trump", group="right", trigger="hype", tone="both",
         source="trump-win-so-much", quote="We're going to win so much.",
         phrases=["win so much"]),
    dict(id="trump-best-words", speaker="trump", group="right", trigger="blunder", tone="funny",
         source="trump-best-words", quote="I know words. I have the best words.",
         phrases=["i have the best words", "i know words"], handful=True),
    dict(id="trump-pwmc", speaker="trump", group="right", trigger="got captured", tone="funny",
         source="trump-pwmc", quote="Person. Woman. Man. Camera. TV.",
         phrases=["person woman man camera", "woman man camera tv"], fate="captured"),
    dict(id="trump-dogs", speaker="trump", group="right", trigger="blunder", tone="both",
         source="trump-dogs", quote="They're eating the dogs… they're eating the cats.",
         phrases=["eating the dogs", "eating the cats"]),
    dict(id="trump-little-marco", speaker="trump", group="right", trigger="trash talk", tone="both",
         source="trump-little-marco", quote="Don't worry about it, Little Marco.",
         phrases=["little marco"]),
    dict(id="trump-no-responsibility", speaker="trump", group="right", trigger="got captured", tone="funny",
         source="trump-no-responsibility", quote="I don't take responsibility at all.",
         phrases=["don't take responsibility at all", "i don't take responsibility"],
         handful=True, fate="fired"),
    # --- Leavitt ---
    dict(id="leavitt-stupid-question", speaker="leavitt", group="right", trigger="trash talk", tone="funny",
         source="leavitt-protests",
         quote="Of course the president supports peaceful protests. What a stupid question.",
         phrases=["stupid question", "supports peaceful protest"],
         t=5.28, t_end=8.56, handful=True),
    # --- Melania ---
    dict(id="melania-dont-care", speaker="melania", group="right", trigger="got captured", tone="both",
         source="melania-abc", quote="I want to show them that I don't care.",
         phrases=["i don't care", "show them that i don't care"], fate="captured"),
    dict(id="melania-wont-stop-me", speaker="melania", group="right", trigger="check", tone="ice-cold",
         source="melania-abc", quote="It will not stop me to do what I feel is right.",
         phrases=["will not stop me", "what i feel is right"]),
    dict(id="melania-wont-be-close", speaker="melania", group="right", trigger="mate", tone="both",
         source="melania-rnc", quote="And it won't even be close.",
         phrases=["won't even be close", "will not even be close"]),
    dict(id="melania-bullied", speaker="melania", group="right", trigger="got captured", tone="both",
         source="melania-abc", quote="I could say that I'm the most bullied person in the world.",
         phrases=["most bullied person"], fate="captured"),
    # --- McConnell ---
    dict(id="mcconnell-reaper", speaker="mcconnell", group="right", trigger="capture", tone="both",
         source="mcconnell-reaper", quote="I am indeed the Grim Reaper.",
         phrases=["grim reaper"], handful=True),
    dict(id="mcconnell-going-anywhere", speaker="mcconnell", group="right", trigger="check", tone="aggressive",
         source="mcconnell-reaper", quote="None of that stuff is going anywhere.",
         phrases=["going anywhere"]),
    dict(id="mcconnell-vacancy", speaker="mcconnell", group="right", trigger="mate", tone="aggressive",
         source="mcconnell-vacancy", quote="Mr. President, you will not fill this Supreme Court vacancy.",
         phrases=["will not fill this supreme court", "supreme court vacancy"]),
    dict(id="mcconnell-let-me-finish", speaker="mcconnell", group="right", trigger="got captured", tone="aggressive",
         source="mcconnell-finish", quote="Let me finish.", phrases=["let me finish"], fate="captured"),
    dict(id="mcconnell-eighth-time", speaker="mcconnell", group="right", trigger="got captured", tone="both",
         source="mcconnell-last-term", quote="I will not seek this honor an eighth time.",
         phrases=["not seek this honor", "eighth time"], handful=True, fate="captured"),
    # --- Rubio ---
    dict(id="rubio-dispel", speaker="rubio", group="right", trigger="got captured", tone="both",
         source="rubio-dispel", quote="Let's dispel with this fiction…",
         phrases=["dispel with this fiction"], handful=True, fate="captured"),
    dict(id="rubio-knows-exactly", speaker="rubio", group="right", trigger="check", tone="aggressive",
         source="rubio-dispel", quote="He knows exactly what he's doing.",
         phrases=["knows exactly what he's doing", "knows exactly what he is doing"]),
    dict(id="rubio-trump-steaks", speaker="rubio", group="right", trigger="trash talk", tone="funny",
         source="rubio-detroit", quote="You ever heard of Trump Steaks?",
         phrases=["trump steaks"]),
    dict(id="rubio-steaks-gone", speaker="rubio", group="right", trigger="capture", tone="both",
         source="rubio-detroit", quote="Trump Steaks is gone.",
         phrases=["steaks is gone", "steaks are gone"]),
    dict(id="rubio-big-donald", speaker="rubio", group="right", trigger="trash talk", tone="funny",
         source="rubio-detroit", quote="Let's hear it, big Donald.",
         phrases=["big donald", "let's hear it"]),
    dict(id="rubio-yoga", speaker="rubio", group="right", trigger="trash talk", tone="funny",
         source="rubio-detroit", quote="When they're done with the yoga, can I answer a question?",
         phrases=["done with the yoga"], handful=True),
    dict(id="rubio-flexible", speaker="rubio", group="right", trigger="trash talk", tone="funny",
         source="rubio-detroit", quote="Well, he's very flexible, so you never know.",
         phrases=["very flexible so you never know", "he's very flexible"], handful=True),
    dict(id="rubio-diplomacy", speaker="rubio", group="right", trigger="hype", tone="both",
         source="rubio-diplomacy",
         quote="We're carrying out diplomacy all over the world constantly and very successfully.",
         phrases=["carrying out diplomacy", "diplomacy all over the world"],
         t=1262.28, t_end=1266.60, handful=True),
    # --- Cruz ---
    dict(id="cruz-coward", speaker="cruz", group="right", trigger="trash talk", tone="aggressive",
         source="cruz-coward", quote="Donald, you're a sniveling coward.",
         phrases=["sniveling coward", "snivelling coward"], handful=True),
    dict(id="cruz-heidi", speaker="cruz", group="right", trigger="trash talk", tone="aggressive",
         source="cruz-coward", quote="Leave Heidi the hell alone.",
         phrases=["leave heidi", "hell alone"]),
    dict(id="cruz-breathe", speaker="cruz", group="right", trigger="got captured", tone="funny",
         source="cruz-breathe", quote="Breathe, breathe, breathe.", phrases=["breathe breathe"],
         fate="captured"),
    dict(id="cruz-cancun", speaker="cruz", group="right", trigger="got captured", tone="funny",
         source="cruz-cancun", quote="It was obviously a mistake.",
         phrases=["obviously a mistake", "it was a mistake"], handful=True, fate="cancun"),
    dict(id="cruz-carpet-bomb", speaker="cruz", group="right", trigger="capture", tone="aggressive",
         source="cruz-carpet", quote="We will carpet bomb them into oblivion.",
         phrases=["carpet bomb", "into oblivion"]),
    dict(id="cruz-conscience", speaker="cruz", group="right", trigger="check", tone="both",
         source="cruz-conscience", quote="Vote your conscience.",
         phrases=["vote your conscience"]),
    dict(id="cruz-chump", speaker="cruz", group="right", trigger="trash talk", tone="aggressive",
         source="cruz-chump", quote="He is playing you for a chump.",
         phrases=["playing you for a chump"]),
    # --- Paul ---
    dict(id="paul-deserve-apology", speaker="paul", group="right", trigger="check", tone="aggressive",
         source="paul-fauci", quote="Frankly, the American people deserve an apology.",
         phrases=["deserve an apology", "american people deserve an apology"],
         t=42.16, t_end=46.04, handful=True),
    # --- RFK ---
    dict(id="rfk-lied-to", speaker="rfk", group="right", trigger="check", tone="aggressive",
         source="rfk-lied", quote="We were lied to about everything.",
         phrases=["lied to about everything"]),
    dict(id="rfk-experts", speaker="rfk", group="right", trigger="trash talk", tone="aggressive",
         source="rfk-experts", quote="We need to stop trusting the experts.",
         phrases=["stop trusting the experts", "trusting the experts"]),
    dict(id="rfk-both-right", speaker="rfk", group="right", trigger="trash talk", tone="funny",
         source="rfk-both-right", quote="They're both right!", phrases=["they're both right", "they are both right"]),
    dict(id="rfk-not-ideal", speaker="rfk", group="right", trigger="got captured", tone="funny",
         source="rfk-not-ideal", quote="I am not an ideal presidential candidate.",
         phrases=["not an ideal presidential candidate"], fate="captured"),
    dict(id="rfk-adhd-focus", speaker="rfk", group="right", trigger="hype", tone="funny",
         source="jre-2461", quote="I have ADHD. I had 11 siblings and I have seven kids. So I can work. I can focus.",
         phrases=["i have adhd", "seven kids", "i can focus"], t=33.65, t_end=41.35, handful=True),
    dict(id="rfk-falconry", speaker="rfk", group="right", trigger="blunder", tone="funny",
         source="jre-2461", quote="My falconry license is New York. My hunting license is New York. My fishing license is New York.",
         phrases=["falconry license", "hunting license is new york"], t=743.05, t_end=748.55, handful=True),
    dict(id="rfk-cyanide", speaker="rfk", group="right", trigger="trash talk", tone="funny",
         source="jre-2461", quote="You can add vitamins to cyanide, and it's not going to make it any better for you.",
         phrases=["vitamins to cyanide", "cyanide"], t=2338.0, t_end=2342.65, handful=True),
    # --- Vance ---
    dict(id="vance-cat-ladies", speaker="vance", group="right", trigger="trash talk", tone="both",
         source="vance-cats", quote="A bunch of childless cat ladies.",
         phrases=["childless cat ladies"]),
    dict(id="vance-trash", speaker="vance", group="right", trigger="capture", tone="aggressive",
         source="vance-trash", quote="We're going to take out the trash… and the trash is named Kamala Harris.",
         phrases=["take out the trash", "trash is named kamala"]),
    dict(id="vance-future", speaker="vance", group="right", trigger="got captured", tone="both",
         source="vance-future", quote="Tim, I'm focused on the future.",
         phrases=["focused on the future"], fate="captured"),
    dict(id="vance-boneheaded", speaker="vance", group="right", trigger="got captured", tone="funny",
         source="vance-boneheaded", quote="Oh man, my most boneheaded comment.",
         phrases=["boneheaded comment", "bone headed"], fate="captured"),
    # --- DeSantis ---
    dict(id="desantis-woke-dies", speaker="desantis", group="right", trigger="mate", tone="aggressive",
         source="desantis-tampa", quote="Florida is where woke goes to die.",
         phrases=["woke goes to die"], t=6 * 60 + 4, handful=True),
    dict(id="desantis-never-surrender", speaker="desantis", group="right", trigger="got captured", tone="aggressive",
         source="desantis-tampa", quote="We will never, ever surrender to the woke mob.",
         phrases=["surrender to the woke"], t=6 * 60 + 4, fate="captured"),
    dict(id="desantis-suspending", speaker="desantis", group="right", trigger="got captured", tone="both",
         source="desantis-suspend", quote="I am today suspending my campaign.",
         phrases=["suspending my campaign", "i am today suspending"], handful=True, fate="captured"),
    dict(id="desantis-begun-to-fight", speaker="desantis", group="right", trigger="hype", tone="aggressive",
         source="desantis-tampa", quote="I have only begun to fight.",
         phrases=["only begun to fight"], t=7 * 60 + 56),
    dict(id="desantis-recovery", speaker="desantis", group="right", trigger="trash talk", tone="both",
         source="desantis-tpusa", quote="I wish the United States of America a speedy recovery from Biden.",
         phrases=["speedy recovery from biden"]),
    dict(id="desantis-end-zone", speaker="desantis", group="right", trigger="capture", tone="both",
         source="desantis-tpusa", quote="It's to put the ball in the end zone.",
         phrases=["ball in the end zone"]),
    # --- Capture orders: king talks about the victim. Filter chip "Captures". ---
    dict(id="trump-vs-harris-comrade", speaker="trump", group="right", trigger="captures", tone="funny",
         source="trump-comrade-kamala", quote="Comrade Kamala Harris.",
         phrases=["comrade kamala", "comrade camala"], target="harris", handful=True,
         t=44.67, t_end=50.11),
    dict(id="trump-vs-harris-lyin", speaker="trump", group="right", trigger="captures", tone="aggressive",
         source="trump-lyin-kamala", quote="Lyin' Kamala Harris.",
         phrases=["lyin kamala", "lying kamala", "lion camala", "new victim to defeat"],
         target="harris", t=45.0, t_end=56.0),
    dict(id="trump-vs-aoc-stupid", speaker="trump", group="right", trigger="captures", tone="funny",
         source="trump-aoc-plus", quote="AOC Plus 3.",
         phrases=["aoc plus", "aoc plus 3"], target="aoc", t=67.35, t_end=73.0),
    dict(id="trump-vs-sanders-crazy", speaker="trump", group="right", trigger="captures", tone="funny",
         source="trump-crazy-bernie", quote="Crazy Bernie.",
         phrases=["crazy bernie"], target="sanders", handful=True, t=11.07, t_end=15.67),
    dict(id="trump-vs-schumer-cryin", speaker="trump", group="right", trigger="captures", tone="funny",
         source="trump-cryin-chuck", quote="Chuck Schumer, crying Chuck.",
         phrases=["crying chuck", "chuck schumer crying"],
         target="schumer", handful=True, t=8.88, t_end=12.5),
    dict(id="trump-vs-warren-pocahontas", speaker="trump", group="right", trigger="captures", tone="funny",
         source="trump-pocahontas", quote="They call her Pocahontas.",
         phrases=["call her pocahontas", "they call her pocahontas"], target="warren", handful=True),
    dict(id="trump-vs-pete-alfred", speaker="trump", group="right", trigger="captures", tone="funny",
         source="trump-vegas-2020", quote="Ladies and gentlemen, introducing President Alfred E. Neuman.",
         phrases=["alfred e neuman", "alfred e newman", "alfred he newman",
                  "ladies and gentlemen introducing"],
         target="buttigieg", t=151.7, t_end=165.0),
    dict(id="trump-vs-mamdani-communist", speaker="trump", group="right", trigger="captures", tone="aggressive",
         source="trump-mamdani-communist", quote="This guy is a communist at the highest level.",
         phrases=["communist at the highest level", "this guy is a communist"],
         target="mamdani", handful=True, t=102.55, t_end=108.0),
    dict(id="trump-vs-activist-lunatics", speaker="trump", group="right", trigger="captures", tone="aggressive",
         source="trump-msg-lunatic", quote="Radical left lunatic.",
         phrases=["radical left lunatic", "radical left lunatics"], target="activist",
         t=102.43, t_end=107.0),
    dict(id="newsom-vs-desantis-outtrump", speaker="newsom", group="left", trigger="captures", tone="funny",
         source="newsom-outtrump-short", quote="So you can out-Trump Trump. And by the way, how's that going for you, Ron?",
         phrases=["out trump trump", "how's that going for you"], target="desantis",
         t=16.3, t_end=22.2),
    dict(id="newsom-vs-vance-phonies", speaker="newsom", group="left", trigger="captures", tone="funny",
         source="newsom-phonies", quote="What frauds. What phonies.",
         phrases=["what frauds", "what phonies"], target="vance", handful=True),
    dict(id="newsom-vs-rubio-phonies", speaker="newsom", group="left", trigger="captures", tone="funny",
         source="newsom-phonies", quote="JD Vance and Marco Rubio were two of the most effective critics of Donald Trump. What frauds. What phonies.",
         phrases=["most effective critics", "what phonies", "what frauds"], target="rubio"),
    dict(id="newsom-vs-maga-knee", speaker="newsom", group="left", trigger="captures", tone="funny",
         source="newsom-knees", quote="New knee pads that I'll be sending out for all these CEOs for bending their knee.",
         phrases=["new knee pads", "bending their knee", "signature siri knee pads"],
         target="maga", t=1444.24, t_end=1458.47),
    dict(id="newsom-vs-cruz-cancun", speaker="newsom", group="left", trigger="captures", tone="funny",
         source="newsom-cancun-cruz", quote="Cancun Cruz.",
         phrases=["cancun cruz"], target="cruz"),
]
