window.CLIPS = [
  {
    "id": "tate-check",
    "speaker": "tate",
    "name": "Andrew Tate",
    "group": "commentators",
    "house": "Booth",
    "trigger": "check",
    "tone": "aggressive",
    "quote": "Check.",
    "handful": false,
    "src": "clips/commentators/tate/tate-check.mp3",
    "url": "https://www.youtube.com/watch?v=NCeAeMJUXqg",
    "duration": 0.571,
    "error": null,
    "extended": "extended/tate-check.mp3",
    "extDuration": 26.593,
    "selStart": 15.7,
    "selEnd": 16.271,
    "padBefore": 15.0,
    "padAfter": 8.883,
    "pieceId": null,
    "bark": false
  },
  {
    "id": "tate-mate-in-two",
    "speaker": "tate",
    "name": "Andrew Tate",
    "group": "commentators",
    "house": "Booth",
    "trigger": "mate",
    "tone": "both",
    "quote": "Mate in two, Piers.",
    "handful": false,
    "src": "clips/commentators/tate/tate-mate-in-two.mp3",
    "url": "https://www.youtube.com/watch?v=NCeAeMJUXqg",
    "duration": 2.38,
    "error": null,
    "extended": "extended/tate-mate-in-two.mp3",
    "extDuration": 26.488,
    "selStart": 15.0,
    "selEnd": 17.38,
    "padBefore": 15.0,
    "padAfter": 9.108,
    "pieceId": null,
    "bark": false
  },
  {
    "id": "tate-check-mate",
    "speaker": "tate",
    "name": "Andrew Tate",
    "group": "commentators",
    "house": "Booth",
    "trigger": "mate",
    "tone": "aggressive",
    "quote": "Check mate.",
    "handful": false,
    "src": "clips/commentators/tate/tate-check-mate.mp3",
    "url": "https://www.youtube.com/watch?v=NCeAeMJUXqg",
    "duration": 7.53,
    "error": null,
    "extended": "extended/tate-check-mate.mp3",
    "extDuration": 36.754,
    "selStart": 15.0,
    "selEnd": 22.53,
    "padBefore": 15.0,
    "padAfter": 14.224,
    "pieceId": null,
    "bark": false
  },
  {
    "id": "tate-good-game",
    "speaker": "tate",
    "name": "Andrew Tate",
    "group": "commentators",
    "house": "Booth",
    "trigger": "mate",
    "tone": "both",
    "quote": "Good game, sir.",
    "handful": false,
    "src": "clips/commentators/tate/tate-good-game.mp3",
    "url": "https://www.youtube.com/watch?v=NCeAeMJUXqg",
    "duration": 3.96,
    "error": null,
    "extended": "extended/tate-good-game.mp3",
    "extDuration": 23.85,
    "selStart": 15.0,
    "selEnd": 18.96,
    "padBefore": 15.0,
    "padAfter": 4.89,
    "pieceId": null,
    "bark": false
  },
  {
    "id": "tate-everything-your-fault",
    "speaker": "tate",
    "name": "Andrew Tate",
    "group": "commentators",
    "house": "Booth",
    "trigger": "blunder",
    "tone": "aggressive",
    "quote": "Absolutely everything is your fault.",
    "handful": false,
    "src": "clips/commentators/tate/tate-everything-your-fault.mp3",
    "url": "https://www.youtube.com/watch?v=zgzF2Nx9DKk",
    "duration": 2.04,
    "error": null,
    "extended": "extended/tate-everything-your-fault.mp3",
    "extDuration": 32.078,
    "selStart": 15.0,
    "selEnd": 17.04,
    "padBefore": 15.0,
    "padAfter": 15.038,
    "pieceId": null,
    "bark": false
  },
  {
    "id": "tate-no-luck",
    "speaker": "tate",
    "name": "Andrew Tate",
    "group": "commentators",
    "house": "Booth",
    "trigger": "blunder",
    "tone": "aggressive",
    "quote": "There is no luck.",
    "handful": false,
    "src": "clips/commentators/tate/tate-no-luck.mp3",
    "url": "https://www.youtube.com/watch?v=NCeAeMJUXqg",
    "duration": 5.998,
    "error": null,
    "extended": "extended/tate-no-luck.mp3",
    "extDuration": 30.798,
    "selStart": 9.752,
    "selEnd": 15.75,
    "padBefore": 15.0,
    "padAfter": 15.048,
    "pieceId": null,
    "bark": false
  },
  {
    "id": "tate-never-give-up",
    "speaker": "tate",
    "name": "Andrew Tate",
    "group": "commentators",
    "house": "Booth",
    "trigger": "hype",
    "tone": "aggressive",
    "quote": "I never ever give up.",
    "handful": true,
    "src": "clips/commentators/tate/tate-never-give-up.mp3",
    "url": "https://www.youtube.com/watch?v=NCeAeMJUXqg",
    "duration": 0.62,
    "error": null,
    "extended": "extended/tate-never-give-up.mp3",
    "extDuration": 30.563,
    "selStart": 15.0,
    "selEnd": 15.62,
    "padBefore": 15.0,
    "padAfter": 15.043,
    "pieceId": null,
    "bark": false
  },
  {
    "id": "tate-chessboard",
    "speaker": "tate",
    "name": "Andrew Tate",
    "group": "commentators",
    "house": "Booth",
    "trigger": "trash talk",
    "tone": "both",
    "quote": "In the chess board of life, I've done pretty good.",
    "handful": false,
    "src": "clips/commentators/tate/tate-chessboard.mp3",
    "url": "https://www.youtube.com/watch?v=NCeAeMJUXqg",
    "duration": 2.16,
    "error": null,
    "extended": "extended/tate-chessboard.mp3",
    "extDuration": 31.922,
    "selStart": 15.372,
    "selEnd": 17.532,
    "padBefore": 15.0,
    "padAfter": 15.042,
    "pieceId": null,
    "bark": false
  },
  {
    "id": "tate-bugatti",
    "speaker": "tate",
    "name": "Andrew Tate",
    "group": "commentators",
    "house": "Booth",
    "trigger": "trash talk",
    "tone": "aggressive",
    "quote": "What color is your Bugatti?",
    "handful": true,
    "src": "clips/commentators/tate/tate-bugatti.mp3",
    "url": "https://www.youtube.com/watch?v=jUXGN-ffKlk",
    "duration": 4.0,
    "error": null,
    "extended": "extended/tate-bugatti.mp3",
    "extDuration": 12.042,
    "selStart": 0.0,
    "selEnd": 4.0,
    "padBefore": 0.0,
    "padAfter": 8.042,
    "pieceId": null,
    "bark": false
  },
  {
    "id": "tate-fuck-off",
    "speaker": "tate",
    "name": "Andrew Tate",
    "group": "commentators",
    "house": "Booth",
    "trigger": "trash talk",
    "tone": "aggressive",
    "quote": "Oh, fuck off then.",
    "handful": false,
    "src": "clips/commentators/tate/tate-fuck-off.mp3",
    "url": "https://www.youtube.com/watch?v=jUXGN-ffKlk",
    "duration": 4.87,
    "error": null,
    "extended": "extended/tate-fuck-off.mp3",
    "extDuration": 12.042,
    "selStart": 7.13,
    "selEnd": 12.0,
    "padBefore": 7.13,
    "padAfter": 0.042,
    "pieceId": null,
    "bark": false
  },
  {
    "id": "tate-shit-together",
    "speaker": "tate",
    "name": "Andrew Tate",
    "group": "commentators",
    "house": "Booth",
    "trigger": "hype",
    "tone": "aggressive",
    "quote": "Get your shit together.",
    "handful": false,
    "src": "clips/commentators/tate/tate-shit-together.mp3",
    "url": "https://www.youtube.com/watch?v=hoBGD8Vq3jI",
    "duration": 2.0,
    "error": null,
    "extended": "extended/tate-shit-together.mp3",
    "extDuration": 16.588,
    "selStart": 1.04,
    "selEnd": 3.04,
    "padBefore": 1.04,
    "padAfter": 13.548,
    "pieceId": null,
    "bark": false
  },
  {
    "id": "tate-you-are-losing",
    "speaker": "tate",
    "name": "Andrew Tate",
    "group": "commentators",
    "house": "Booth",
    "trigger": "check",
    "tone": "aggressive",
    "quote": "You are losing.",
    "handful": false,
    "src": "clips/commentators/tate/tate-you-are-losing.mp3",
    "url": "https://www.youtube.com/watch?v=O6IYkROsMRg",
    "duration": 30.041,
    "error": null,
    "extended": "extended/tate-you-are-losing.mp3",
    "extDuration": 30.041,
    "selStart": 0.0,
    "selEnd": 30.041,
    "padBefore": 0.0,
    "padAfter": 0.0,
    "pieceId": null,
    "bark": false
  },
  {
    "id": "rogan-its-over",
    "speaker": "rogan",
    "name": "Joe Rogan",
    "group": "commentators",
    "house": "Booth",
    "trigger": "capture",
    "tone": "booth",
    "quote": "It's over!",
    "handful": false,
    "src": null,
    "url": "https://www.youtube.com/watch?v=coBJjmYhUbc",
    "duration": null,
    "error": "quote not found in captions/audio",
    "extended": null,
    "extDuration": null,
    "selStart": null,
    "selEnd": null,
    "padBefore": null,
    "padAfter": null,
    "pieceId": null,
    "bark": false
  },
  {
    "id": "rogan-he-is-out",
    "speaker": "rogan",
    "name": "Joe Rogan",
    "group": "commentators",
    "house": "Booth",
    "trigger": "capture",
    "tone": "booth",
    "quote": "He is out! / Oh, he's out. He's out.",
    "handful": false,
    "src": null,
    "url": "https://www.youtube.com/watch?v=coBJjmYhUbc",
    "duration": null,
    "error": "quote not found in captions/audio",
    "extended": null,
    "extDuration": null,
    "selStart": null,
    "selEnd": null,
    "padBefore": null,
    "padAfter": null,
    "pieceId": null,
    "bark": false
  },
  {
    "id": "rogan-comeback",
    "speaker": "rogan",
    "name": "Joe Rogan",
    "group": "commentators",
    "house": "Booth",
    "trigger": "mate",
    "tone": "booth",
    "quote": "The most amazing comeback I have ever seen.",
    "handful": false,
    "src": null,
    "url": "https://www.youtube.com/watch?v=coBJjmYhUbc",
    "duration": null,
    "error": "quote not found in captions/audio",
    "extended": null,
    "extDuration": null,
    "selStart": null,
    "selEnd": null,
    "padBefore": null,
    "padAfter": null,
    "pieceId": null,
    "bark": false
  },
  {
    "id": "rogan-so-clean",
    "speaker": "rogan",
    "name": "Joe Rogan",
    "group": "commentators",
    "house": "Booth",
    "trigger": "capture",
    "tone": "booth",
    "quote": "That was so clean!",
    "handful": false,
    "src": null,
    "url": "https://www.youtube.com/watch?v=I-0PrblKnwo",
    "duration": null,
    "error": "quote not found in captions/audio",
    "extended": null,
    "extDuration": null,
    "selStart": null,
    "selEnd": null,
    "padBefore": null,
    "padAfter": null,
    "pieceId": null,
    "bark": false
  },
  {
    "id": "rogan-dariush",
    "speaker": "rogan",
    "name": "Joe Rogan",
    "group": "commentators",
    "house": "Booth",
    "trigger": "check",
    "tone": "booth",
    "quote": "Dariush is in real trouble.",
    "handful": false,
    "src": "clips/commentators/rogan/rogan-dariush.mp3",
    "url": "https://www.youtube.com/watch?v=62no1FlWb2o",
    "duration": 10.971,
    "error": null,
    "extended": "extended/rogan-dariush.mp3",
    "extDuration": 10.971,
    "selStart": 0.0,
    "selEnd": 10.971,
    "padBefore": 0.0,
    "padAfter": 0.0,
    "pieceId": null,
    "bark": false
  },
  {
    "id": "rogan-omg",
    "speaker": "rogan",
    "name": "Joe Rogan",
    "group": "commentators",
    "house": "Booth",
    "trigger": "mate",
    "tone": "booth",
    "quote": "Oh my God!",
    "handful": false,
    "src": "clips/commentators/rogan/rogan-omg.mp3",
    "url": "https://www.youtube.com/watch?v=62no1FlWb2o",
    "duration": 10.0,
    "error": null,
    "extended": "extended/rogan-omg.mp3",
    "extDuration": 10.971,
    "selStart": 0.0,
    "selEnd": 10.0,
    "padBefore": 0.0,
    "padAfter": 0.971,
    "pieceId": null,
    "bark": false
  },
  {
    "id": "rogan-crazy",
    "speaker": "rogan",
    "name": "Joe Rogan",
    "group": "commentators",
    "house": "Booth",
    "trigger": "blunder",
    "tone": "booth",
    "quote": "This is crazy.",
    "handful": false,
    "src": "clips/commentators/rogan/rogan-crazy.mp3",
    "url": "https://www.youtube.com/watch?v=64V0TKZVUK4",
    "duration": 4.0,
    "error": null,
    "extended": "extended/rogan-crazy.mp3",
    "extDuration": 24.059,
    "selStart": 5.0,
    "selEnd": 9.0,
    "padBefore": 5.0,
    "padAfter": 15.059,
    "pieceId": null,
    "bark": false
  },
  {
    "id": "rogan-jamie",
    "speaker": "rogan",
    "name": "Joe Rogan",
    "group": "commentators",
    "house": "Booth",
    "trigger": "hype",
    "tone": "booth",
    "quote": "Jamie, pull that up.",
    "handful": false,
    "src": "clips/commentators/rogan/rogan-jamie.mp3",
    "url": "https://www.youtube.com/watch?v=SRgct4c5T5U",
    "duration": 4.0,
    "error": null,
    "extended": "extended/rogan-jamie.mp3",
    "extDuration": 13.035,
    "selStart": 2.0,
    "selEnd": 6.0,
    "padBefore": 2.0,
    "padAfter": 7.035,
    "pieceId": null,
    "bark": false
  },
  {
    "id": "rogan-bananas",
    "speaker": "rogan",
    "name": "Joe Rogan",
    "group": "commentators",
    "house": "Booth",
    "trigger": "blunder",
    "tone": "booth",
    "quote": "It was bananas.",
    "handful": false,
    "src": "clips/commentators/rogan/rogan-bananas.mp3",
    "url": "https://www.youtube.com/watch?v=Up3_ORIeUrk",
    "duration": 13.035,
    "error": null,
    "extended": "extended/rogan-bananas.mp3",
    "extDuration": 13.035,
    "selStart": 0.0,
    "selEnd": 13.035,
    "padBefore": 0.0,
    "padAfter": 0.0,
    "pieceId": null,
    "bark": false
  },
  {
    "id": "rogan-shocker",
    "speaker": "rogan",
    "name": "Joe Rogan",
    "group": "commentators",
    "house": "Booth",
    "trigger": "blunder",
    "tone": "booth",
    "quote": "What a shocker.",
    "handful": false,
    "src": null,
    "url": "https://www.youtube.com/watch?v=z4U-PzrMZ1w",
    "duration": null,
    "error": "quote not found in captions/audio",
    "extended": null,
    "extDuration": null,
    "selStart": null,
    "selEnd": null,
    "padBefore": null,
    "padAfter": null,
    "pieceId": null,
    "bark": false
  },
  {
    "id": "newsom-hows-that",
    "speaker": "newsom",
    "name": "Newsom",
    "group": "left",
    "house": "The Left",
    "trigger": "trash talk",
    "tone": "both",
    "quote": "How's that going for you, Ron?",
    "handful": false,
    "src": "clips/left/newsom/newsom-hows-that.mp3",
    "url": "https://www.youtube.com/watch?v=COzAPK5XQG4",
    "duration": 1.845,
    "error": null,
    "extended": "extended/newsom-hows-that.mp3",
    "extDuration": 32.444,
    "selStart": 14.583,
    "selEnd": 16.428,
    "padBefore": 15.0,
    "padAfter": 15.044,
    "pieceId": "newsom",
    "bark": false
  },
  {
    "id": "newsom-bully",
    "speaker": "newsom",
    "name": "Newsom",
    "group": "left",
    "house": "The Left",
    "trigger": "capture",
    "tone": "aggressive",
    "quote": "You're nothing but a bully.",
    "handful": true,
    "src": null,
    "url": "https://www.youtube.com/watch?v=g_TOyzk3FFc",
    "duration": null,
    "error": "quote not found in captions/audio",
    "extended": null,
    "extDuration": null,
    "selStart": null,
    "selEnd": null,
    "padBefore": null,
    "padAfter": null,
    "pieceId": "newsom",
    "bark": false
  },
  {
    "id": "newsom-relax",
    "speaker": "newsom",
    "name": "Newsom",
    "group": "left",
    "house": "The Left",
    "trigger": "got captured",
    "tone": "both",
    "quote": "Again, Ron, relax. I can handle it.",
    "handful": false,
    "src": null,
    "url": "https://www.youtube.com/watch?v=llGdKZyCOEQ",
    "duration": null,
    "error": "quote not found in captions/audio",
    "extended": null,
    "extDuration": null,
    "selStart": null,
    "selEnd": null,
    "padBefore": null,
    "padAfter": null,
    "pieceId": "newsom",
    "bark": false
  },
  {
    "id": "newsom-used-to-bullying",
    "speaker": "newsom",
    "name": "Newsom",
    "group": "left",
    "house": "The Left",
    "trigger": "got captured",
    "tone": "funny",
    "quote": "I'm used to bullying.",
    "handful": false,
    "src": null,
    "url": "https://www.youtube.com/watch?v=3pSW8-3Zth0",
    "duration": null,
    "error": "quote not found in captions/audio",
    "extended": null,
    "extDuration": null,
    "selStart": null,
    "selEnd": null,
    "padBefore": null,
    "padAfter": null,
    "pieceId": "newsom",
    "bark": false
  },
  {
    "id": "newsom-spare-me",
    "speaker": "newsom",
    "name": "Newsom",
    "group": "left",
    "house": "The Left",
    "trigger": "trash talk",
    "tone": "aggressive",
    "quote": "Spare me this notion of freedom.",
    "handful": false,
    "src": null,
    "url": "https://www.youtube.com/watch?v=RODOXvwdh6c",
    "duration": null,
    "error": "quote not found in captions/audio",
    "extended": null,
    "extDuration": null,
    "selStart": null,
    "selEnd": null,
    "padBefore": null,
    "padAfter": null,
    "pieceId": "newsom",
    "bark": false
  },
  {
    "id": "newsom-fire",
    "speaker": "newsom",
    "name": "Newsom",
    "group": "left",
    "house": "The Left",
    "trigger": "hype",
    "tone": "aggressive",
    "quote": "Fight fire with fire.",
    "handful": false,
    "src": null,
    "url": "https://www.youtube.com/watch?v=9-eypG77UH0",
    "duration": null,
    "error": "quote not found in captions/audio",
    "extended": null,
    "extDuration": null,
    "selStart": null,
    "selEnd": null,
    "padBefore": null,
    "padAfter": null,
    "pieceId": "newsom",
    "bark": false
  },
  {
    "id": "aoc-lied-to",
    "speaker": "aoc",
    "name": "AOC",
    "group": "left",
    "house": "The Left",
    "trigger": "blunder",
    "tone": "both",
    "quote": "It doesn't take a smart person to know if you're being lied to.",
    "handful": false,
    "src": "clips/left/aoc/aoc-lied-to.mp3",
    "url": "https://www.youtube.com/watch?v=rcgw7Nt4L9M",
    "duration": 4.0,
    "error": null,
    "extended": "extended/aoc-lied-to.mp3",
    "extDuration": 34.038,
    "selStart": 15.0,
    "selEnd": 19.0,
    "padBefore": 15.0,
    "padAfter": 15.038,
    "pieceId": "aoc",
    "bark": false
  },
  {
    "id": "aoc-lying",
    "speaker": "aoc",
    "name": "AOC",
    "group": "left",
    "house": "The Left",
    "trigger": "check",
    "tone": "aggressive",
    "quote": "You're either being lied to or you are lying.",
    "handful": false,
    "src": null,
    "url": "https://www.youtube.com/watch?v=rcgw7Nt4L9M",
    "duration": null,
    "error": "quote not found in captions/audio",
    "extended": null,
    "extDuration": null,
    "selStart": null,
    "selEnd": null,
    "padBefore": null,
    "padAfter": null,
    "pieceId": "aoc",
    "bark": false
  },
  {
    "id": "aoc-devil",
    "speaker": "aoc",
    "name": "AOC",
    "group": "left",
    "house": "The Left",
    "trigger": "mate",
    "tone": "aggressive",
    "quote": "This bill is a deal with the devil.",
    "handful": false,
    "src": "clips/left/aoc/aoc-devil.mp3",
    "url": "https://www.youtube.com/watch?v=rcgw7Nt4L9M",
    "duration": 3.997,
    "error": null,
    "extended": "extended/aoc-devil.mp3",
    "extDuration": 36.049,
    "selStart": 16.725,
    "selEnd": 20.722,
    "padBefore": 15.0,
    "padAfter": 15.049,
    "pieceId": "aoc",
    "bark": true
  },
  {
    "id": "aoc-beat-them",
    "speaker": "aoc",
    "name": "AOC",
    "group": "left",
    "house": "The Left",
    "trigger": "hype",
    "tone": "aggressive",
    "quote": "We are going to beat them.",
    "handful": false,
    "src": "clips/left/aoc/aoc-beat-them.mp3",
    "url": "https://www.youtube.com/watch?v=C232Zq_MUFA",
    "duration": 3.003,
    "error": null,
    "extended": "extended/aoc-beat-them.mp3",
    "extDuration": 33.567,
    "selStart": 15.359,
    "selEnd": 18.362,
    "padBefore": 15.0,
    "padAfter": 15.047,
    "pieceId": "aoc",
    "bark": true
  },
  {
    "id": "bernie-damn-bill",
    "speaker": "bernie",
    "name": "Bernie",
    "group": "left",
    "house": "The Left",
    "trigger": "capture",
    "tone": "both",
    "quote": "I wrote the damn bill.",
    "handful": true,
    "src": "clips/left/bernie/bernie-damn-bill.mp3",
    "url": "https://www.youtube.com/watch?v=vuroOJWk3DI",
    "duration": 2.28,
    "error": null,
    "extended": "extended/bernie-damn-bill.mp3",
    "extDuration": 18.625,
    "selStart": 15.0,
    "selEnd": 17.28,
    "padBefore": 15.0,
    "padAfter": 1.345,
    "pieceId": "sanders",
    "bark": false
  },
  {
    "id": "bernie-youre-wrong",
    "speaker": "bernie",
    "name": "Bernie",
    "group": "left",
    "house": "The Left",
    "trigger": "blunder",
    "tone": "aggressive",
    "quote": "You're wrong.",
    "handful": false,
    "src": "clips/left/bernie/bernie-youre-wrong.mp3",
    "url": "https://www.youtube.com/watch?v=jrh1C0HSRhM",
    "duration": 1.974,
    "error": null,
    "extended": "extended/bernie-youre-wrong.mp3",
    "extDuration": 35.422,
    "selStart": 18.642,
    "selEnd": 20.616,
    "padBefore": 15.0,
    "padAfter": 15.032,
    "pieceId": "sanders",
    "bark": true
  },
  {
    "id": "bernie-not-me-us",
    "speaker": "bernie",
    "name": "Bernie",
    "group": "left",
    "house": "The Left",
    "trigger": "hype",
    "tone": "aggressive",
    "quote": "Not me. Us.",
    "handful": false,
    "src": "clips/left/bernie/bernie-not-me-us.mp3",
    "url": "https://www.youtube.com/watch?v=OADlaeggv14",
    "duration": 2.89,
    "error": null,
    "extended": "extended/bernie-not-me-us.mp3",
    "extDuration": 32.94,
    "selStart": 15.0,
    "selEnd": 17.89,
    "padBefore": 15.0,
    "padAfter": 15.05,
    "pieceId": "sanders",
    "bark": false
  },
  {
    "id": "schumer-whirlwind",
    "speaker": "schumer",
    "name": "Schumer",
    "group": "left",
    "house": "The Left",
    "trigger": "check",
    "tone": "aggressive",
    "quote": "You have released the whirlwind.",
    "handful": false,
    "src": "clips/left/schumer/schumer-whirlwind.mp3",
    "url": "https://www.youtube.com/watch?v=qHGrzoS9AbE",
    "duration": 5.625,
    "error": null,
    "extended": "extended/schumer-whirlwind.mp3",
    "extDuration": 33.358,
    "selStart": 15.883,
    "selEnd": 21.508,
    "padBefore": 15.0,
    "padAfter": 15.038,
    "pieceId": "schumer",
    "bark": true
  },
  {
    "id": "schumer-pay-the-price",
    "speaker": "schumer",
    "name": "Schumer",
    "group": "left",
    "house": "The Left",
    "trigger": "capture",
    "tone": "aggressive",
    "quote": "You will pay the price.",
    "handful": false,
    "src": "clips/left/schumer/schumer-pay-the-price.mp3",
    "url": "https://www.youtube.com/watch?v=qHGrzoS9AbE",
    "duration": 5.96,
    "error": null,
    "extended": "extended/schumer-pay-the-price.mp3",
    "extDuration": 35.997,
    "selStart": 15.0,
    "selEnd": 20.96,
    "padBefore": 15.0,
    "padAfter": 15.037,
    "pieceId": "schumer",
    "bark": false
  },
  {
    "id": "schumer-what-hit-you",
    "speaker": "schumer",
    "name": "Schumer",
    "group": "left",
    "house": "The Left",
    "trigger": "mate",
    "tone": "aggressive",
    "quote": "You won't know what hit you.",
    "handful": true,
    "src": "clips/left/schumer/schumer-what-hit-you.mp3",
    "url": "https://www.youtube.com/watch?v=qHGrzoS9AbE",
    "duration": 7.0,
    "error": null,
    "extended": "extended/schumer-what-hit-you.mp3",
    "extDuration": 37.042,
    "selStart": 15.0,
    "selEnd": 22.0,
    "padBefore": 15.0,
    "padAfter": 15.042,
    "pieceId": "schumer",
    "bark": false
  },
  {
    "id": "schumer-gone-november",
    "speaker": "schumer",
    "name": "Schumer",
    "group": "left",
    "house": "The Left",
    "trigger": "mate",
    "tone": "aggressive",
    "quote": "You're gone in November.",
    "handful": false,
    "src": "clips/left/schumer/schumer-gone-november.mp3",
    "url": "https://www.youtube.com/watch?v=qHGrzoS9AbE",
    "duration": 1.813,
    "error": null,
    "extended": "extended/schumer-gone-november.mp3",
    "extDuration": 31.582,
    "selStart": 14.545,
    "selEnd": 16.358,
    "padBefore": 15.0,
    "padAfter": 15.052,
    "pieceId": "schumer",
    "bark": true
  },
  {
    "id": "schumer-not-on-our-watch",
    "speaker": "schumer",
    "name": "Schumer",
    "group": "left",
    "house": "The Left",
    "trigger": "got captured",
    "tone": "aggressive",
    "quote": "Not on our watch.",
    "handful": false,
    "src": "clips/left/schumer/schumer-not-on-our-watch.mp3",
    "url": "https://www.youtube.com/watch?v=qHGrzoS9AbE",
    "duration": 4.112,
    "error": null,
    "extended": "extended/schumer-not-on-our-watch.mp3",
    "extDuration": 33.123,
    "selStart": 13.545,
    "selEnd": 17.657,
    "padBefore": 15.0,
    "padAfter": 15.033,
    "pieceId": "schumer",
    "bark": true
  },
  {
    "id": "schumer-brooklyn",
    "speaker": "schumer",
    "name": "Schumer",
    "group": "left",
    "house": "The Left",
    "trigger": "got captured",
    "tone": "both",
    "quote": "I'm from Brooklyn. We speak in strong language.",
    "handful": false,
    "src": null,
    "url": "https://www.youtube.com/watch?v=qamnB92fK5E",
    "duration": null,
    "error": "quote not found in captions/audio",
    "extended": null,
    "extDuration": null,
    "selStart": null,
    "selEnd": null,
    "padBefore": null,
    "padAfter": null,
    "pieceId": "schumer",
    "bark": false
  },
  {
    "id": "kamala-im-speaking",
    "speaker": "kamala",
    "name": "Kamala",
    "group": "left",
    "house": "The Left",
    "trigger": "got captured",
    "tone": "both",
    "quote": "I'm speaking. / Mr. Vice President, I'm speaking.",
    "handful": true,
    "src": "clips/left/kamala/kamala-im-speaking.mp3",
    "url": "https://www.youtube.com/watch?v=tXFqTGBty1w",
    "duration": 1.47,
    "error": null,
    "extended": "extended/kamala-im-speaking.mp3",
    "extDuration": 24.895,
    "selStart": 8.38,
    "selEnd": 9.85,
    "padBefore": 8.38,
    "padAfter": 15.045,
    "pieceId": "harris",
    "bark": false
  },
  {
    "id": "kamala-we-did-it",
    "speaker": "kamala",
    "name": "Kamala",
    "group": "left",
    "house": "The Left",
    "trigger": "mate",
    "tone": "funny",
    "quote": "We did it, Joe.",
    "handful": true,
    "src": "clips/left/kamala/kamala-we-did-it.mp3",
    "url": "https://www.youtube.com/watch?v=H3lpFE19T78",
    "duration": 8.315,
    "error": null,
    "extended": "extended/kamala-we-did-it.mp3",
    "extDuration": 15.047,
    "selStart": 0.816,
    "selEnd": 9.131,
    "padBefore": 2.73,
    "padAfter": 10.327,
    "pieceId": "harris",
    "bark": false
  },
  {
    "id": "kamala-running-against-me",
    "speaker": "kamala",
    "name": "Kamala",
    "group": "left",
    "house": "The Left",
    "trigger": "trash talk",
    "tone": "both",
    "quote": "You're running against me.",
    "handful": false,
    "src": null,
    "url": "https://www.youtube.com/watch?v=OQgE0ETV81s",
    "duration": null,
    "error": "quote not found in captions/audio",
    "extended": null,
    "extDuration": null,
    "selStart": null,
    "selEnd": null,
    "padBefore": null,
    "padAfter": null,
    "pieceId": "harris",
    "bark": false
  },
  {
    "id": "kamala-not-going-back",
    "speaker": "kamala",
    "name": "Kamala",
    "group": "left",
    "house": "The Left",
    "trigger": "hype",
    "tone": "aggressive",
    "quote": "We're not going back.",
    "handful": false,
    "src": null,
    "url": "https://www.youtube.com/watch?v=OQgE0ETV81s",
    "duration": null,
    "error": "quote not found in captions/audio",
    "extended": null,
    "extDuration": null,
    "selStart": null,
    "selEnd": null,
    "padBefore": null,
    "padAfter": null,
    "pieceId": "harris",
    "bark": false
  },
  {
    "id": "kamala-coconut",
    "speaker": "kamala",
    "name": "Kamala",
    "group": "left",
    "house": "The Left",
    "trigger": "blunder",
    "tone": "funny",
    "quote": "You think you just fell out of a coconut tree?",
    "handful": true,
    "src": "clips/left/kamala/kamala-coconut.mp3",
    "url": "https://www.youtube.com/watch?v=0bSTqokjNEE",
    "duration": 6.839,
    "error": null,
    "extended": "extended/kamala-coconut.mp3",
    "extDuration": 34.56,
    "selStart": 14.675,
    "selEnd": 21.514,
    "padBefore": 15.0,
    "padAfter": 15.03,
    "pieceId": "harris",
    "bark": true
  },
  {
    "id": "warren-plan",
    "speaker": "warren",
    "name": "Warren",
    "group": "left",
    "house": "The Left",
    "trigger": "hype",
    "tone": "funny",
    "quote": "I have a plan for that.",
    "handful": false,
    "src": "clips/left/warren/warren-plan.mp3",
    "url": "https://www.youtube.com/watch?v=o7y35Jb9cP8",
    "duration": 12.58,
    "error": null,
    "extended": "extended/warren-plan.mp3",
    "extDuration": 36.336,
    "selStart": 8.72,
    "selEnd": 21.3,
    "padBefore": 8.72,
    "padAfter": 15.036,
    "pieceId": "warren",
    "bark": false
  },
  {
    "id": "warren-bloomberg",
    "speaker": "warren",
    "name": "Warren",
    "group": "left",
    "house": "The Left",
    "trigger": "capture",
    "tone": "both",
    "quote": "No, I'm not talking about Donald Trump. I'm talking about Mayor Bloomberg.",
    "handful": false,
    "src": "clips/left/warren/warren-bloomberg.mp3",
    "url": "https://www.youtube.com/watch?v=QD4csGWPo6o",
    "duration": 1.92,
    "error": null,
    "extended": "extended/warren-bloomberg.mp3",
    "extDuration": 27.559,
    "selStart": 10.6,
    "selEnd": 12.52,
    "padBefore": 10.6,
    "padAfter": 15.039,
    "pieceId": "warren",
    "bark": false
  },
  {
    "id": "warren-wine-caves",
    "speaker": "warren",
    "name": "Warren",
    "group": "left",
    "house": "The Left",
    "trigger": "trash talk",
    "tone": "both",
    "quote": "Billionaires in wine caves should not pick the next president.",
    "handful": false,
    "src": "clips/left/warren/warren-wine-caves.mp3",
    "url": "https://www.youtube.com/watch?v=CMgQu1GjSmk",
    "duration": 2.88,
    "error": null,
    "extended": "extended/warren-wine-caves.mp3",
    "extDuration": 32.914,
    "selStart": 15.0,
    "selEnd": 17.88,
    "padBefore": 15.0,
    "padAfter": 15.034,
    "pieceId": "warren",
    "bark": false
  },
  {
    "id": "warren-not-silent",
    "speaker": "warren",
    "name": "Warren",
    "group": "left",
    "house": "The Left",
    "trigger": "got captured",
    "tone": "aggressive",
    "quote": "I will not be silent.",
    "handful": false,
    "src": null,
    "url": "https://www.youtube.com/watch?v=GOEMxZe4tY0",
    "duration": null,
    "error": "quote not found in captions/audio",
    "extended": null,
    "extDuration": null,
    "selStart": null,
    "selEnd": null,
    "padBefore": null,
    "padAfter": null,
    "pieceId": "warren",
    "bark": false
  },
  {
    "id": "pete-bait",
    "speaker": "buttigieg",
    "name": "Mayor Pete",
    "group": "left",
    "house": "The Left",
    "trigger": "blunder",
    "tone": "both",
    "quote": "I know bait when I see it, and I'm not going to take it.",
    "handful": false,
    "src": null,
    "url": "https://www.youtube.com/watch?v=bMxD7_KCwto",
    "duration": null,
    "error": "quote not found in captions/audio",
    "extended": null,
    "extDuration": null,
    "selStart": null,
    "selEnd": null,
    "padBefore": null,
    "padAfter": null,
    "pieceId": "buttigieg",
    "bark": false
  },
  {
    "id": "pete-quarrel",
    "speaker": "buttigieg",
    "name": "Mayor Pete",
    "group": "left",
    "house": "The Left",
    "trigger": "trash talk",
    "tone": "aggressive",
    "quote": "Your quarrel, sir, is with my creator.",
    "handful": false,
    "src": "clips/left/buttigieg/pete-quarrel.mp3",
    "url": "https://www.youtube.com/watch?v=hViAbRitbmw",
    "duration": 3.88,
    "error": null,
    "extended": "extended/pete-quarrel.mp3",
    "extDuration": 33.907,
    "selStart": 15.0,
    "selEnd": 18.88,
    "padBefore": 15.0,
    "padAfter": 15.027,
    "pieceId": "buttigieg",
    "bark": false
  },
  {
    "id": "pete-data",
    "speaker": "buttigieg",
    "name": "Mayor Pete",
    "group": "left",
    "house": "The Left",
    "trigger": "trash talk",
    "tone": "both",
    "quote": "Do yourself a favor and look up the data.",
    "handful": false,
    "src": "clips/left/buttigieg/pete-data.mp3",
    "url": "https://www.youtube.com/watch?v=QzGEotTYsCE",
    "duration": 4.15,
    "error": null,
    "extended": "extended/pete-data.mp3",
    "extDuration": 34.22,
    "selStart": 15.0,
    "selEnd": 19.15,
    "padBefore": 15.0,
    "padAfter": 15.03,
    "pieceId": "buttigieg",
    "bark": true
  },
  {
    "id": "pete-literally",
    "speaker": "buttigieg",
    "name": "Mayor Pete",
    "group": "left",
    "house": "The Left",
    "trigger": "blunder",
    "tone": "aggressive",
    "quote": "That's literally not true.",
    "handful": false,
    "src": null,
    "url": "",
    "duration": null,
    "error": "could not resolve source",
    "extended": null,
    "extDuration": null,
    "selStart": null,
    "selEnd": null,
    "padBefore": null,
    "padAfter": null,
    "pieceId": "buttigieg",
    "bark": false
  },
  {
    "id": "mamdani-volume",
    "speaker": "mamdani",
    "name": "Mamdani",
    "group": "left",
    "house": "The Left",
    "trigger": "check",
    "tone": "both",
    "quote": "Turn the volume up.",
    "handful": true,
    "src": "clips/left/mamdani/mamdani-volume.mp3",
    "url": "https://www.youtube.com/watch?v=NoyVRSeh_4o",
    "duration": 24.28,
    "error": null,
    "extended": "extended/mamdani-volume.mp3",
    "extDuration": 53.76,
    "selStart": 15.0,
    "selEnd": 39.28,
    "padBefore": 15.0,
    "padAfter": 14.48,
    "pieceId": "mamdani",
    "bark": false
  },
  {
    "id": "mamdani-get-through",
    "speaker": "mamdani",
    "name": "Mamdani",
    "group": "left",
    "house": "The Left",
    "trigger": "check",
    "tone": "aggressive",
    "quote": "To get to any of us, you will have to get through all of us.",
    "handful": false,
    "src": "clips/left/mamdani/mamdani-get-through.mp3",
    "url": "https://www.youtube.com/watch?v=hFH2dYwH3rI",
    "duration": 5.33,
    "error": null,
    "extended": "extended/mamdani-get-through.mp3",
    "extDuration": 35.37,
    "selStart": 15.0,
    "selEnd": 20.33,
    "padBefore": 15.0,
    "padAfter": 15.04,
    "pieceId": "mamdani",
    "bark": false
  },
  {
    "id": "mamdani-dynasty",
    "speaker": "mamdani",
    "name": "Mamdani",
    "group": "left",
    "house": "The Left",
    "trigger": "mate",
    "tone": "both",
    "quote": "We have toppled a political dynasty.",
    "handful": false,
    "src": "clips/left/mamdani/mamdani-dynasty.mp3",
    "url": "https://www.youtube.com/watch?v=GDXky5HLHos",
    "duration": 7.07,
    "error": null,
    "extended": "extended/mamdani-dynasty.mp3",
    "extDuration": 37.12,
    "selStart": 15.0,
    "selEnd": 22.07,
    "padBefore": 15.0,
    "padAfter": 15.05,
    "pieceId": "mamdani",
    "bark": false
  },
  {
    "id": "mamdani-his-name",
    "speaker": "mamdani",
    "name": "Mamdani",
    "group": "left",
    "house": "The Left",
    "trigger": "capture",
    "tone": "both",
    "quote": "Let tonight be the final time I utter his name.",
    "handful": false,
    "src": "clips/left/mamdani/mamdani-his-name.mp3",
    "url": "https://www.youtube.com/watch?v=hFH2dYwH3rI",
    "duration": 3.839,
    "error": null,
    "extended": "extended/mamdani-his-name.mp3",
    "extDuration": 33.463,
    "selStart": 12.798,
    "selEnd": 16.637,
    "padBefore": 15.0,
    "padAfter": 15.033,
    "pieceId": "mamdani",
    "bark": true
  },
  {
    "id": "trump-fired",
    "speaker": "trump",
    "name": "Trump",
    "group": "right",
    "house": "The Right",
    "trigger": "capture",
    "tone": "aggressive",
    "quote": "You are fired. Get out.",
    "handful": true,
    "src": "clips/right/trump/trump-fired.mp3",
    "url": "https://www.youtube.com/watch?v=8TBkt7os9EY",
    "duration": 5.27,
    "error": null,
    "extended": "extended/trump-fired.mp3",
    "extDuration": 26.436,
    "selStart": 15.0,
    "selEnd": 20.27,
    "padBefore": 15.0,
    "padAfter": 6.166,
    "pieceId": "trump",
    "bark": false
  },
  {
    "id": "trump-jail",
    "speaker": "trump",
    "name": "Trump",
    "group": "right",
    "house": "The Right",
    "trigger": "capture",
    "tone": "both",
    "quote": "Because you'd be in jail.",
    "handful": true,
    "src": "clips/right/trump/trump-jail.mp3",
    "url": "https://www.youtube.com/watch?v=_XzL1sQWRd4",
    "duration": 4.55,
    "error": null,
    "extended": "extended/trump-jail.mp3",
    "extDuration": 13.845,
    "selStart": 3.93,
    "selEnd": 8.48,
    "padBefore": 3.93,
    "padAfter": 5.365,
    "pieceId": "trump",
    "bark": false
  },
  {
    "id": "trump-nasty-woman",
    "speaker": "trump",
    "name": "Trump",
    "group": "right",
    "house": "The Right",
    "trigger": "trash talk",
    "tone": "aggressive",
    "quote": "Such a nasty woman.",
    "handful": false,
    "src": "clips/right/trump/trump-nasty-woman.mp3",
    "url": "https://www.youtube.com/watch?v=B2dXhjNRwpE",
    "duration": 29.0,
    "error": null,
    "extended": "extended/trump-nasty-woman.mp3",
    "extDuration": 29.048,
    "selStart": 0.0,
    "selEnd": 29.0,
    "padBefore": 0.0,
    "padAfter": 0.048,
    "pieceId": "trump",
    "bark": false
  },
  {
    "id": "trump-alone-fix",
    "speaker": "trump",
    "name": "Trump",
    "group": "right",
    "house": "The Right",
    "trigger": "hype",
    "tone": "aggressive",
    "quote": "I alone can fix it.",
    "handful": false,
    "src": "clips/right/trump/trump-alone-fix.mp3",
    "url": "https://www.youtube.com/watch?v=QctsdtGEttY",
    "duration": 2.347,
    "error": null,
    "extended": "extended/trump-alone-fix.mp3",
    "extDuration": 19.043,
    "selStart": 1.874,
    "selEnd": 4.221,
    "padBefore": 0.0,
    "padAfter": 1.603,
    "pieceId": "trump",
    "bark": true
  },
  {
    "id": "trump-your-voice",
    "speaker": "trump",
    "name": "Trump",
    "group": "right",
    "house": "The Right",
    "trigger": "hype",
    "tone": "aggressive",
    "quote": "I am your voice.",
    "handful": false,
    "src": "clips/right/trump/trump-your-voice.mp3",
    "url": "https://www.youtube.com/watch?v=QctsdtGEttY",
    "duration": 19.043,
    "error": null,
    "extended": "extended/trump-your-voice.mp3",
    "extDuration": 19.043,
    "selStart": 0.0,
    "selEnd": 19.043,
    "padBefore": 0.0,
    "padAfter": 0.0,
    "pieceId": "trump",
    "bark": false
  },
  {
    "id": "trump-win-so-much",
    "speaker": "trump",
    "name": "Trump",
    "group": "right",
    "house": "The Right",
    "trigger": "hype",
    "tone": "both",
    "quote": "We're going to win so much.",
    "handful": false,
    "src": "clips/right/trump/trump-win-so-much.mp3",
    "url": "https://www.youtube.com/watch?v=nOMPk1N2RiY",
    "duration": 13.0,
    "error": null,
    "extended": "extended/trump-win-so-much.mp3",
    "extDuration": 13.035,
    "selStart": 0.0,
    "selEnd": 13.0,
    "padBefore": 0.0,
    "padAfter": 0.035,
    "pieceId": "trump",
    "bark": false
  },
  {
    "id": "trump-best-words",
    "speaker": "trump",
    "name": "Trump",
    "group": "right",
    "house": "The Right",
    "trigger": "blunder",
    "tone": "funny",
    "quote": "I know words. I have the best words.",
    "handful": true,
    "src": "clips/right/trump/trump-best-words.mp3",
    "url": "https://www.youtube.com/watch?v=IIVtO5UmQZQ",
    "duration": 1.91,
    "error": null,
    "extended": "extended/trump-best-words.mp3",
    "extDuration": 19.696,
    "selStart": 2.74,
    "selEnd": 4.65,
    "padBefore": 2.74,
    "padAfter": 15.046,
    "pieceId": "trump",
    "bark": false
  },
  {
    "id": "trump-pwmc",
    "speaker": "trump",
    "name": "Trump",
    "group": "right",
    "house": "The Right",
    "trigger": "blunder",
    "tone": "funny",
    "quote": "Person. Woman. Man. Camera. TV.",
    "handful": false,
    "src": "clips/right/trump/trump-pwmc.mp3",
    "url": "https://www.youtube.com/watch?v=1S2J9AN2AFo",
    "duration": 5.76,
    "error": null,
    "extended": "extended/trump-pwmc.mp3",
    "extDuration": 33.176,
    "selStart": 12.37,
    "selEnd": 18.13,
    "padBefore": 12.37,
    "padAfter": 15.046,
    "pieceId": "trump",
    "bark": false
  },
  {
    "id": "trump-dogs",
    "speaker": "trump",
    "name": "Trump",
    "group": "right",
    "house": "The Right",
    "trigger": "blunder",
    "tone": "both",
    "quote": "They're eating the dogs\u2026 they're eating the cats.",
    "handful": false,
    "src": "clips/right/trump/trump-dogs.mp3",
    "url": "https://www.youtube.com/watch?v=MBJX7aRG5NI",
    "duration": 17.36,
    "error": null,
    "extended": "extended/trump-dogs.mp3",
    "extDuration": 47.386,
    "selStart": 15.0,
    "selEnd": 32.36,
    "padBefore": 15.0,
    "padAfter": 15.026,
    "pieceId": "trump",
    "bark": false
  },
  {
    "id": "trump-little-marco",
    "speaker": "trump",
    "name": "Trump",
    "group": "right",
    "house": "The Right",
    "trigger": "trash talk",
    "tone": "both",
    "quote": "Don't worry about it, Little Marco.",
    "handful": false,
    "src": "clips/right/trump/trump-little-marco.mp3",
    "url": "https://www.youtube.com/watch?v=7p_ltuXcOH4",
    "duration": 2.77,
    "error": null,
    "extended": "extended/trump-little-marco.mp3",
    "extDuration": 23.902,
    "selStart": 6.09,
    "selEnd": 8.86,
    "padBefore": 6.09,
    "padAfter": 15.042,
    "pieceId": "trump",
    "bark": false
  },
  {
    "id": "melania-dont-care",
    "speaker": "melania",
    "name": "Melania",
    "group": "right",
    "house": "The Right",
    "trigger": "trash talk",
    "tone": "both",
    "quote": "I want to show them that I don't care.",
    "handful": false,
    "src": "clips/right/melania/melania-dont-care.mp3",
    "url": "https://www.youtube.com/watch?v=MmQ-i6xYmuo",
    "duration": 2.23,
    "error": null,
    "extended": "extended/melania-dont-care.mp3",
    "extDuration": 32.261,
    "selStart": 15.0,
    "selEnd": 17.23,
    "padBefore": 15.0,
    "padAfter": 15.031,
    "pieceId": "melania",
    "bark": false
  },
  {
    "id": "melania-wont-stop-me",
    "speaker": "melania",
    "name": "Melania",
    "group": "right",
    "house": "The Right",
    "trigger": "check",
    "tone": "ice-cold",
    "quote": "It will not stop me to do what I feel is right.",
    "handful": false,
    "src": "clips/right/melania/melania-wont-stop-me.mp3",
    "url": "https://www.youtube.com/watch?v=_igQrYQdTVQ",
    "duration": 5.94,
    "error": null,
    "extended": "extended/melania-wont-stop-me.mp3",
    "extDuration": 35.971,
    "selStart": 15.0,
    "selEnd": 20.94,
    "padBefore": 15.0,
    "padAfter": 15.031,
    "pieceId": "melania",
    "bark": false
  },
  {
    "id": "melania-wont-be-close",
    "speaker": "melania",
    "name": "Melania",
    "group": "right",
    "house": "The Right",
    "trigger": "mate",
    "tone": "both",
    "quote": "And it won't even be close.",
    "handful": false,
    "src": null,
    "url": "https://www.youtube.com/watch?v=oUj2UzJ4uA8",
    "duration": null,
    "error": "quote not found in captions/audio",
    "extended": null,
    "extDuration": null,
    "selStart": null,
    "selEnd": null,
    "padBefore": null,
    "padAfter": null,
    "pieceId": "melania",
    "bark": false
  },
  {
    "id": "melania-bullied",
    "speaker": "melania",
    "name": "Melania",
    "group": "right",
    "house": "The Right",
    "trigger": "got captured",
    "tone": "both",
    "quote": "I could say that I'm the most bullied person in the world.",
    "handful": false,
    "src": "clips/right/melania/melania-bullied.mp3",
    "url": "https://www.youtube.com/watch?v=MmQ-i6xYmuo",
    "duration": 3.38,
    "error": null,
    "extended": "extended/melania-bullied.mp3",
    "extDuration": 33.411,
    "selStart": 15.0,
    "selEnd": 18.38,
    "padBefore": 15.0,
    "padAfter": 15.031,
    "pieceId": "melania",
    "bark": false
  },
  {
    "id": "mcconnell-reaper",
    "speaker": "mcconnell",
    "name": "McConnell",
    "group": "right",
    "house": "The Right",
    "trigger": "capture",
    "tone": "both",
    "quote": "I am indeed the Grim Reaper.",
    "handful": true,
    "src": "clips/right/mcconnell/mcconnell-reaper.mp3",
    "url": "https://www.youtube.com/watch?v=w5vIJPSN4zw",
    "duration": 3.14,
    "error": null,
    "extended": "extended/mcconnell-reaper.mp3",
    "extDuration": 33.176,
    "selStart": 15.0,
    "selEnd": 18.14,
    "padBefore": 15.0,
    "padAfter": 15.036,
    "pieceId": "mcconnell",
    "bark": false
  },
  {
    "id": "mcconnell-going-anywhere",
    "speaker": "mcconnell",
    "name": "McConnell",
    "group": "right",
    "house": "The Right",
    "trigger": "check",
    "tone": "aggressive",
    "quote": "None of that stuff is going anywhere.",
    "handful": false,
    "src": "clips/right/mcconnell/mcconnell-going-anywhere.mp3",
    "url": "https://www.youtube.com/watch?v=w5vIJPSN4zw",
    "duration": 7.33,
    "error": null,
    "extended": "extended/mcconnell-going-anywhere.mp3",
    "extDuration": 37.381,
    "selStart": 15.0,
    "selEnd": 22.33,
    "padBefore": 15.0,
    "padAfter": 15.051,
    "pieceId": "mcconnell",
    "bark": false
  },
  {
    "id": "mcconnell-vacancy",
    "speaker": "mcconnell",
    "name": "McConnell",
    "group": "right",
    "house": "The Right",
    "trigger": "mate",
    "tone": "aggressive",
    "quote": "Mr. President, you will not fill this Supreme Court vacancy.",
    "handful": false,
    "src": null,
    "url": "https://www.youtube.com/watch?v=ZcKYOGWyamY",
    "duration": null,
    "error": "quote not found in captions/audio",
    "extended": null,
    "extDuration": null,
    "selStart": null,
    "selEnd": null,
    "padBefore": null,
    "padAfter": null,
    "pieceId": "mcconnell",
    "bark": false
  },
  {
    "id": "mcconnell-let-me-finish",
    "speaker": "mcconnell",
    "name": "McConnell",
    "group": "right",
    "house": "The Right",
    "trigger": "trash talk",
    "tone": "aggressive",
    "quote": "Let me finish.",
    "handful": false,
    "src": "clips/right/mcconnell/mcconnell-let-me-finish.mp3",
    "url": "https://www.youtube.com/watch?v=YKp6k46CJ7o",
    "duration": 42.527,
    "error": null,
    "extended": "extended/mcconnell-let-me-finish.mp3",
    "extDuration": 42.527,
    "selStart": 0.0,
    "selEnd": 42.527,
    "padBefore": 0.0,
    "padAfter": 0.0,
    "pieceId": "mcconnell",
    "bark": false
  },
  {
    "id": "rubio-dispel",
    "speaker": "rubio",
    "name": "Rubio",
    "group": "right",
    "house": "The Right",
    "trigger": "blunder",
    "tone": "both",
    "quote": "Let's dispel with this fiction\u2026",
    "handful": true,
    "src": "clips/right/rubio/rubio-dispel.mp3",
    "url": "https://www.youtube.com/watch?v=CkdpzRDxTXU",
    "duration": 1.22,
    "error": null,
    "extended": "extended/rubio-dispel.mp3",
    "extDuration": 31.269,
    "selStart": 15.0,
    "selEnd": 16.22,
    "padBefore": 15.0,
    "padAfter": 15.049,
    "pieceId": "rubio",
    "bark": false
  },
  {
    "id": "rubio-knows-exactly",
    "speaker": "rubio",
    "name": "Rubio",
    "group": "right",
    "house": "The Right",
    "trigger": "check",
    "tone": "aggressive",
    "quote": "He knows exactly what he's doing.",
    "handful": false,
    "src": "clips/right/rubio/rubio-knows-exactly.mp3",
    "url": "https://www.youtube.com/watch?v=CkdpzRDxTXU",
    "duration": 2.17,
    "error": null,
    "extended": "extended/rubio-knows-exactly.mp3",
    "extDuration": 32.209,
    "selStart": 15.0,
    "selEnd": 17.17,
    "padBefore": 15.0,
    "padAfter": 15.039,
    "pieceId": "rubio",
    "bark": false
  },
  {
    "id": "rubio-trump-steaks",
    "speaker": "rubio",
    "name": "Rubio",
    "group": "right",
    "house": "The Right",
    "trigger": "trash talk",
    "tone": "funny",
    "quote": "You ever heard of Trump Steaks?",
    "handful": false,
    "src": null,
    "url": "https://www.youtube.com/watch?v=CR0k5xdUxBs",
    "duration": null,
    "error": "quote not found in captions/audio",
    "extended": null,
    "extDuration": null,
    "selStart": null,
    "selEnd": null,
    "padBefore": null,
    "padAfter": null,
    "pieceId": "rubio",
    "bark": false
  },
  {
    "id": "rubio-steaks-gone",
    "speaker": "rubio",
    "name": "Rubio",
    "group": "right",
    "house": "The Right",
    "trigger": "capture",
    "tone": "both",
    "quote": "Trump Steaks is gone.",
    "handful": false,
    "src": null,
    "url": "https://www.youtube.com/watch?v=CR0k5xdUxBs",
    "duration": null,
    "error": "quote not found in captions/audio",
    "extended": null,
    "extDuration": null,
    "selStart": null,
    "selEnd": null,
    "padBefore": null,
    "padAfter": null,
    "pieceId": "rubio",
    "bark": false
  },
  {
    "id": "rubio-big-donald",
    "speaker": "rubio",
    "name": "Rubio",
    "group": "right",
    "house": "The Right",
    "trigger": "trash talk",
    "tone": "funny",
    "quote": "Let's hear it, big Donald.",
    "handful": false,
    "src": null,
    "url": "https://www.youtube.com/watch?v=CR0k5xdUxBs",
    "duration": null,
    "error": "quote not found in captions/audio",
    "extended": null,
    "extDuration": null,
    "selStart": null,
    "selEnd": null,
    "padBefore": null,
    "padAfter": null,
    "pieceId": "rubio",
    "bark": false
  },
  {
    "id": "rubio-yoga",
    "speaker": "rubio",
    "name": "Rubio",
    "group": "right",
    "house": "The Right",
    "trigger": "trash talk",
    "tone": "funny",
    "quote": "When they're done with the yoga, can I answer a question?",
    "handful": false,
    "src": null,
    "url": "https://www.youtube.com/watch?v=CR0k5xdUxBs",
    "duration": null,
    "error": "quote not found in captions/audio",
    "extended": null,
    "extDuration": null,
    "selStart": null,
    "selEnd": null,
    "padBefore": null,
    "padAfter": null,
    "pieceId": "rubio",
    "bark": false
  },
  {
    "id": "cruz-coward",
    "speaker": "cruz",
    "name": "Cruz",
    "group": "right",
    "house": "The Right",
    "trigger": "trash talk",
    "tone": "aggressive",
    "quote": "Donald, you're a sniveling coward.",
    "handful": true,
    "src": "clips/right/cruz/cruz-coward.mp3",
    "url": "https://www.youtube.com/watch?v=p_qBjmvywYs",
    "duration": 2.07,
    "error": null,
    "extended": "extended/cruz-coward.mp3",
    "extDuration": 27.193,
    "selStart": 10.08,
    "selEnd": 12.15,
    "padBefore": 10.08,
    "padAfter": 15.043,
    "pieceId": "cruz",
    "bark": false
  },
  {
    "id": "cruz-heidi",
    "speaker": "cruz",
    "name": "Cruz",
    "group": "right",
    "house": "The Right",
    "trigger": "trash talk",
    "tone": "aggressive",
    "quote": "Leave Heidi the hell alone.",
    "handful": false,
    "src": "clips/right/cruz/cruz-heidi.mp3",
    "url": "https://www.youtube.com/watch?v=p_qBjmvywYs",
    "duration": 1.01,
    "error": null,
    "extended": "extended/cruz-heidi.mp3",
    "extDuration": 28.264,
    "selStart": 12.22,
    "selEnd": 13.23,
    "padBefore": 12.22,
    "padAfter": 15.034,
    "pieceId": "cruz",
    "bark": false
  },
  {
    "id": "cruz-breathe",
    "speaker": "cruz",
    "name": "Cruz",
    "group": "right",
    "house": "The Right",
    "trigger": "trash talk",
    "tone": "funny",
    "quote": "Breathe, breathe, breathe.",
    "handful": false,
    "src": "clips/right/cruz/cruz-breathe.mp3",
    "url": "https://www.youtube.com/watch?v=vJpmEeIrFzw",
    "duration": 1.28,
    "error": null,
    "extended": "extended/cruz-breathe.mp3",
    "extDuration": 31.321,
    "selStart": 15.0,
    "selEnd": 16.28,
    "padBefore": 15.0,
    "padAfter": 15.041,
    "pieceId": "cruz",
    "bark": false
  },
  {
    "id": "cruz-carpet-bomb",
    "speaker": "cruz",
    "name": "Cruz",
    "group": "right",
    "house": "The Right",
    "trigger": "capture",
    "tone": "aggressive",
    "quote": "We will carpet bomb them into oblivion.",
    "handful": false,
    "src": "clips/right/cruz/cruz-carpet-bomb.mp3",
    "url": "https://www.youtube.com/watch?v=XFMCdevBznQ",
    "duration": 4.58,
    "error": null,
    "extended": "extended/cruz-carpet-bomb.mp3",
    "extDuration": 34.612,
    "selStart": 15.0,
    "selEnd": 19.58,
    "padBefore": 15.0,
    "padAfter": 15.032,
    "pieceId": "cruz",
    "bark": false
  },
  {
    "id": "cruz-conscience",
    "speaker": "cruz",
    "name": "Cruz",
    "group": "right",
    "house": "The Right",
    "trigger": "check",
    "tone": "both",
    "quote": "Vote your conscience.",
    "handful": false,
    "src": "clips/right/cruz/cruz-conscience.mp3",
    "url": "https://www.youtube.com/watch?v=orX-rWiMPCE",
    "duration": 1.95,
    "error": null,
    "extended": "extended/cruz-conscience.mp3",
    "extDuration": 32.0,
    "selStart": 15.0,
    "selEnd": 16.95,
    "padBefore": 15.0,
    "padAfter": 15.05,
    "pieceId": "cruz",
    "bark": false
  },
  {
    "id": "cruz-chump",
    "speaker": "cruz",
    "name": "Cruz",
    "group": "right",
    "house": "The Right",
    "trigger": "trash talk",
    "tone": "aggressive",
    "quote": "He is playing you for a chump.",
    "handful": false,
    "src": "clips/right/cruz/cruz-chump.mp3",
    "url": "https://www.youtube.com/watch?v=5osvk4lMQFQ",
    "duration": 6.0,
    "error": null,
    "extended": "extended/cruz-chump.mp3",
    "extDuration": 36.049,
    "selStart": 15.0,
    "selEnd": 21.0,
    "padBefore": 15.0,
    "padAfter": 15.049,
    "pieceId": "cruz",
    "bark": false
  },
  {
    "id": "rfk-lied-to",
    "speaker": "rfk",
    "name": "RFK Jr.",
    "group": "right",
    "house": "The Right",
    "trigger": "check",
    "tone": "aggressive",
    "quote": "We were lied to about everything.",
    "handful": false,
    "src": "clips/right/rfk/rfk-lied-to.mp3",
    "url": "https://www.youtube.com/watch?v=OBpVLYmYLso",
    "duration": 7.52,
    "error": null,
    "extended": "extended/rfk-lied-to.mp3",
    "extDuration": 27.402,
    "selStart": 4.84,
    "selEnd": 12.36,
    "padBefore": 4.84,
    "padAfter": 15.042,
    "pieceId": "rfk",
    "bark": false
  },
  {
    "id": "rfk-experts",
    "speaker": "rfk",
    "name": "RFK Jr.",
    "group": "right",
    "house": "The Right",
    "trigger": "trash talk",
    "tone": "aggressive",
    "quote": "We need to stop trusting the experts.",
    "handful": false,
    "src": null,
    "url": "https://www.youtube.com/watch?v=3au1duKY5rM",
    "duration": null,
    "error": "quote not found in captions/audio",
    "extended": null,
    "extDuration": null,
    "selStart": null,
    "selEnd": null,
    "padBefore": null,
    "padAfter": null,
    "pieceId": "rfk",
    "bark": false
  },
  {
    "id": "rfk-both-right",
    "speaker": "rfk",
    "name": "RFK Jr.",
    "group": "right",
    "house": "The Right",
    "trigger": "trash talk",
    "tone": "funny",
    "quote": "They're both right!",
    "handful": false,
    "src": "clips/right/rfk/rfk-both-right.mp3",
    "url": "https://www.youtube.com/watch?v=0WiyWQoHi94",
    "duration": 6.52,
    "error": null,
    "extended": "extended/rfk-both-right.mp3",
    "extDuration": 36.571,
    "selStart": 15.0,
    "selEnd": 21.52,
    "padBefore": 15.0,
    "padAfter": 15.051,
    "pieceId": "rfk",
    "bark": false
  },
  {
    "id": "rfk-not-ideal",
    "speaker": "rfk",
    "name": "RFK Jr.",
    "group": "right",
    "house": "The Right",
    "trigger": "blunder",
    "tone": "funny",
    "quote": "I am not an ideal presidential candidate.",
    "handful": false,
    "src": "clips/right/rfk/rfk-not-ideal.mp3",
    "url": "https://www.youtube.com/watch?v=RTRBVh045m8",
    "duration": 2.2,
    "error": null,
    "extended": "extended/rfk-not-ideal.mp3",
    "extDuration": 32.235,
    "selStart": 15.0,
    "selEnd": 17.2,
    "padBefore": 15.0,
    "padAfter": 15.035,
    "pieceId": "rfk",
    "bark": false
  },
  {
    "id": "vance-cat-ladies",
    "speaker": "vance",
    "name": "Vance",
    "group": "right",
    "house": "The Right",
    "trigger": "trash talk",
    "tone": "both",
    "quote": "A bunch of childless cat ladies.",
    "handful": false,
    "src": "clips/right/vance/vance-cat-ladies.mp3",
    "url": "https://www.youtube.com/watch?v=Ba8_gHiByQY",
    "duration": 3.91,
    "error": null,
    "extended": "extended/vance-cat-ladies.mp3",
    "extDuration": 33.959,
    "selStart": 15.0,
    "selEnd": 18.91,
    "padBefore": 15.0,
    "padAfter": 15.049,
    "pieceId": "vance",
    "bark": false
  },
  {
    "id": "vance-trash",
    "speaker": "vance",
    "name": "Vance",
    "group": "right",
    "house": "The Right",
    "trigger": "capture",
    "tone": "aggressive",
    "quote": "We're going to take out the trash\u2026 and the trash is named Kamala Harris.",
    "handful": false,
    "src": "clips/right/vance/vance-trash.mp3",
    "url": "https://www.youtube.com/watch?v=nZkJJNtlr0o",
    "duration": 5.119,
    "error": null,
    "extended": "extended/vance-trash.mp3",
    "extDuration": 31.295,
    "selStart": 15.0,
    "selEnd": 20.119,
    "padBefore": 15.0,
    "padAfter": 15.035,
    "pieceId": "vance",
    "bark": true
  },
  {
    "id": "vance-future",
    "speaker": "vance",
    "name": "Vance",
    "group": "right",
    "house": "The Right",
    "trigger": "got captured",
    "tone": "both",
    "quote": "Tim, I'm focused on the future.",
    "handful": false,
    "src": "clips/right/vance/vance-future.mp3",
    "url": "https://www.youtube.com/watch?v=tpj163BPdWA",
    "duration": 43.52,
    "error": null,
    "extended": "extended/vance-future.mp3",
    "extDuration": 43.52,
    "selStart": 0.0,
    "selEnd": 43.52,
    "padBefore": 0.0,
    "padAfter": 0.0,
    "pieceId": "vance",
    "bark": false
  },
  {
    "id": "vance-boneheaded",
    "speaker": "vance",
    "name": "Vance",
    "group": "right",
    "house": "The Right",
    "trigger": "got captured",
    "tone": "funny",
    "quote": "Oh man, my most boneheaded comment.",
    "handful": false,
    "src": "clips/right/vance/vance-boneheaded.mp3",
    "url": "https://www.youtube.com/watch?v=lZSAop2-UH8",
    "duration": 8.16,
    "error": null,
    "extended": "extended/vance-boneheaded.mp3",
    "extDuration": 33.593,
    "selStart": 10.4,
    "selEnd": 18.56,
    "padBefore": 10.4,
    "padAfter": 15.033,
    "pieceId": "vance",
    "bark": false
  },
  {
    "id": "desantis-woke-dies",
    "speaker": "desantis",
    "name": "DeSantis",
    "group": "right",
    "house": "The Right",
    "trigger": "mate",
    "tone": "aggressive",
    "quote": "Florida is where woke goes to die.",
    "handful": true,
    "src": "clips/right/desantis/desantis-woke-dies.mp3",
    "url": "https://www.youtube.com/watch?v=xfmrQOXk9bM",
    "duration": 8.35,
    "error": null,
    "extended": "extended/desantis-woke-dies.mp3",
    "extDuration": 38.4,
    "selStart": 15.0,
    "selEnd": 23.35,
    "padBefore": 15.0,
    "padAfter": 15.05,
    "pieceId": "desantis",
    "bark": false
  },
  {
    "id": "desantis-never-surrender",
    "speaker": "desantis",
    "name": "DeSantis",
    "group": "right",
    "house": "The Right",
    "trigger": "check",
    "tone": "aggressive",
    "quote": "We will never, ever surrender to the woke mob.",
    "handful": false,
    "src": "clips/right/desantis/desantis-never-surrender.mp3",
    "url": "https://www.youtube.com/watch?v=xfmrQOXk9bM",
    "duration": 3.533,
    "error": null,
    "extended": "extended/desantis-never-surrender.mp3",
    "extDuration": 33.28,
    "selStart": 15.075,
    "selEnd": 18.608,
    "padBefore": 15.0,
    "padAfter": 15.05,
    "pieceId": "desantis",
    "bark": true
  },
  {
    "id": "desantis-begun-to-fight",
    "speaker": "desantis",
    "name": "DeSantis",
    "group": "right",
    "house": "The Right",
    "trigger": "hype",
    "tone": "aggressive",
    "quote": "I have only begun to fight.",
    "handful": false,
    "src": "clips/right/desantis/desantis-begun-to-fight.mp3",
    "url": "https://www.youtube.com/watch?v=xfmrQOXk9bM",
    "duration": 2.25,
    "error": null,
    "extended": "extended/desantis-begun-to-fight.mp3",
    "extDuration": 32.287,
    "selStart": 15.0,
    "selEnd": 17.25,
    "padBefore": 15.0,
    "padAfter": 15.037,
    "pieceId": "desantis",
    "bark": false
  },
  {
    "id": "desantis-recovery",
    "speaker": "desantis",
    "name": "DeSantis",
    "group": "right",
    "house": "The Right",
    "trigger": "trash talk",
    "tone": "both",
    "quote": "I wish the United States of America a speedy recovery from Biden.",
    "handful": false,
    "src": null,
    "url": "",
    "duration": null,
    "error": "could not resolve source",
    "extended": null,
    "extDuration": null,
    "selStart": null,
    "selEnd": null,
    "padBefore": null,
    "padAfter": null,
    "pieceId": "desantis",
    "bark": false
  },
  {
    "id": "desantis-end-zone",
    "speaker": "desantis",
    "name": "DeSantis",
    "group": "right",
    "house": "The Right",
    "trigger": "capture",
    "tone": "both",
    "quote": "It's to put the ball in the end zone.",
    "handful": false,
    "src": null,
    "url": "",
    "duration": null,
    "error": "could not resolve source",
    "extended": null,
    "extDuration": null,
    "selStart": null,
    "selEnd": null,
    "padBefore": null,
    "padAfter": null,
    "pieceId": "desantis",
    "bark": false
  }
];
